/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN13ConfigManager17setOffsetSequenceEiP12JDBankOffsetib.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN13ConfigManager17setOffsetSequenceEiP12JDBankOffsetib()');
  },

  onLeave(log, retval, state) {
  }
});
