/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN15UnCompressedP2P13fixEs2AbsSkewEiRK12_JasperCalibR24JasperCalibAbsSkewPreset.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN15UnCompressedP2P13fixEs2AbsSkewEiRK12_JasperCalibR24JasperCalibAbsSkewPreset()');
  },

  onLeave(log, retval, state) {
  }
});
