/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN25gmoCoreAnalyticsTelemetry25setSpotsDepthDistributionEPPfPPbjNSt3__15arrayI13OperationModeLm4EEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN25gmoCoreAnalyticsTelemetry25setSpotsDepthDistributionEPPfPPbjNSt3__15arrayI13OperationModeLm4EEE()');
  },

  onLeave(log, retval, state) {
  }
});
