/*
 * Auto-generated by Frida. Please modify to match the signature of $s5UIKit26UIListContentConfigurationV24directionalLayoutMarginsSo23NSDirectionalEdgeInsetsVvg.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s5UIKit26UIListContentConfigurationV24directionalLayoutMarginsSo23NSDirectionalEdgeInsetsVvg()');
  },

  onLeave(log, retval, state) {
  }
});
