/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo18UIPointerAccessoryC5UIKitE8PositionV6offset5angleAE12CoreGraphics7CGFloatV_AJtcfC.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo18UIPointerAccessoryC5UIKitE8PositionV6offset5angleAE12CoreGraphics7CGFloatV_AJtcfC()');
  },

  onLeave(log, retval, state) {
  }
});
