/*
 * Auto-generated by Frida. Please modify to match the signature of $s7SwiftUI10EdgeInsetsV7TipsUI2E02uicD0So06UIEdgeD0Vvg.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s7SwiftUI10EdgeInsetsV7TipsUI2E02uicD0So06UIEdgeD0Vvg()');
  },

  onLeave(log, retval, state) {
  }
});
