/*
 * Auto-generated by Frida. Please modify to match the signature of $s7TipsUI29AssetViewVyA2C0D5ModelCcfC.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s7TipsUI29AssetViewVyA2C0D5ModelCcfC()');
  },

  onLeave(log, retval, state) {
  }
});
