/*
 * Auto-generated by Frida. Please modify to match the signature of $s7TipsUI29AssetViewV0D5ModelC10$tintColor7Combine9PublishedV9PublisherVy7SwiftUI0G0V_GvM.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s7TipsUI29AssetViewV0D5ModelC10$tintColor7Combine9PublishedV9PublisherVy7SwiftUI0G0V_GvM()');
  },

  onLeave(log, retval, state) {
  }
});
