/*
 * Auto-generated by Frida. Please modify to match the signature of _Z22ValidateTransposeLayerRK18ZinIrHalParametersRKNSt3__16vectorI16DimensionMappingNS2_9allocatorIS4_EEEER19ZinTensorDimensionsSB_RNS2_3setIPK10__CFStringNS2_4lessISF_EENS5_ISF_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_Z22ValidateTransposeLayerRK18ZinIrHalParametersRKNSt3__16vectorI16DimensionMappingNS2_9allocatorIS4_EEEER19ZinTensorDimensionsSB_RNS2_3setIPK10__CFStringNS2_4lessISF_EENS5_ISF_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
