/*
 * Auto-generated by Frida. Please modify to match the signature of _Z23GetMinMaxNormDimensionsRK23ZinIrMinMaxNormUnitInfoRNSt3__113unordered_setI14ZinIrDimensionNS2_4hashIS4_EENS2_8equal_toIS4_EENS2_9allocatorIS4_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_Z23GetMinMaxNormDimensionsRK23ZinIrMinMaxNormUnitInfoRNSt3__113unordered_setI14ZinIrDimensionNS2_4hashIS4_EENS2_8equal_toIS4_EENS2_9allocatorIS4_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
