/*
 * Auto-generated by Frida. Please modify to match the signature of _Z23UpdateDimensionAndError14ZinIrDimensionmR19ZinTensorDimensionsRNSt3__13setIPK10__CFStringNS2_4lessIS6_EENS2_9allocatorIS6_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_Z23UpdateDimensionAndError14ZinIrDimensionmR19ZinTensorDimensionsRNSt3__13setIPK10__CFStringNS2_4lessIS6_EENS2_9allocatorIS6_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
