/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN18ZinIrScheduleGraph33CompressPerfectChainFromGivenNodeERK18ZinIrHalParametersP12ZinIrOpLayerRNSt3__113unordered_setIS4_NS5_4hashIS4_EENS5_8equal_toIS4_EENS5_9allocatorIS4_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN18ZinIrScheduleGraph33CompressPerfectChainFromGivenNodeERK18ZinIrHalParametersP12ZinIrOpLayerRNSt3__113unordered_setIS4_NS5_4hashIS4_EENS5_8equal_toIS4_EENS5_9allocatorIS4_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
