/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN17ZinIrOpLayerGraph17MoveOutgoingEdgesEP12ZinIrOpLayerS1_NSt3__113unordered_setIS1_NS2_4hashIS1_EENS2_8equal_toIS1_EENS2_9allocatorIS1_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN17ZinIrOpLayerGraph17MoveOutgoingEdgesEP12ZinIrOpLayerS1_NSt3__113unordered_setIS1_NS2_4hashIS1_EENS2_8equal_toIS1_EENS2_9allocatorIS1_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
