/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN18ZinIrScheduleGraph21CompressPerfectChainsERK18ZinIrHalParametersRNSt3__113unordered_setIP12ZinIrOpLayerNS3_4hashIS6_EENS3_8equal_toIS6_EENS3_9allocatorIS6_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN18ZinIrScheduleGraph21CompressPerfectChainsERK18ZinIrHalParametersRNSt3__113unordered_setIP12ZinIrOpLayerNS3_4hashIS6_EENS3_8equal_toIS6_EENS3_9allocatorIS6_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
