/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN11ZinMirHoist14FindCandidatesEP12ZinIrOpLayerRNSt3__16vectorINS2_10shared_ptrI10ZinPatternEENS2_9allocatorIS6_EEEERNS2_13unordered_setIS1_NS2_4hashIS1_EENS2_8equal_toIS1_EENS7_IS1_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN11ZinMirHoist14FindCandidatesEP12ZinIrOpLayerRNSt3__16vectorINS2_10shared_ptrI10ZinPatternEENS2_9allocatorIS6_EEEERNS2_13unordered_setIS1_NS2_4hashIS1_EENS2_8equal_toIS1_EENS7_IS1_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
