/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN17LayerTilingHelper6CreateERKNSt3__13setIP12ZinIrOpLayer15ZinIrComparatorIS2_ENS0_9allocatorIS3_EEEERNS0_13unordered_mapIS3_S_NS0_4hashIS3_EENS0_8equal_toIS3_EENS6_INS0_4pairIKS3_S_EEEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN17LayerTilingHelper6CreateERKNSt3__13setIP12ZinIrOpLayer15ZinIrComparatorIS2_ENS0_9allocatorIS3_EEEERNS0_13unordered_mapIS3_S_NS0_4hashIS3_EENS0_8equal_toIS3_EENS6_INS0_4pairIKS3_S_EEEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
