/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN19ZinL2NormLayerUtils17ConstructSubUnitsERK18ZinIrHalParametersRKNSt3__113unordered_setI14ZinIrDimensionNS3_4hashIS5_EENS3_8equal_toIS5_EENS3_9allocatorIS5_EEEERKNS3_6vectorINS_20L2NormDecomposedDescENSA_ISG_EEEERKNS3_12basic_stringIcNS3_11char_traitsIcEENSA_IcEEEERNSF_I15ZinIrTensorInfoNSA_ISS_EEEERNSF_INS3_10unique_ptrI9ZinIrUnitNS3_14default_deleteISX_EEEENSA_IS10_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN19ZinL2NormLayerUtils17ConstructSubUnitsERK18ZinIrHalParametersRKNSt3__113unordered_setI14ZinIrDimensionNS3_4hashIS5_EENS3_8equal_toIS5_EENS3_9allocatorIS5_EEEERKNS3_6vectorINS_20L2NormDecomposedDescENSA_ISG_EEEERKNS3_12basic_stringIcNS3_11char_traitsIcEENSA_IcEEEERNSF_I15ZinIrTensorInfoNSA_ISS_EEEERNSF_INS3_10unique_ptrI9ZinIrUnitNS3_14default_deleteISX_EEEENSA_IS10_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
