/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN17ZinIrRegAllocUtil23ComputeDependencyOffsetERKNSt3__16vectorINS1_IP12ZinIrOpLayerNS0_9allocatorIS3_EEEENS4_IS6_EEEEPK14ZinEngineLayerSD_PK17ZinIrOpLayerGraphRK18ZinIrHalParameters14DependencyType.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN17ZinIrRegAllocUtil23ComputeDependencyOffsetERKNSt3__16vectorINS1_IP12ZinIrOpLayerNS0_9allocatorIS3_EEEENS4_IS6_EEEEPK14ZinEngineLayerSD_PK17ZinIrOpLayerGraphRK18ZinIrHalParameters14DependencyType()');
  },

  onLeave(log, retval, state) {
  }
});
