/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN10ZinBuilder20CreateLayerNormLayerEP12ZinIrContextR20ZinObjectNameFactoryRK19ZinTensorDimensionsRKNSt3__113unordered_setI14ZinIrDimensionNS7_4hashIS9_EENS7_8equal_toIS9_EENS7_9allocatorIS9_EEEEfl.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN10ZinBuilder20CreateLayerNormLayerEP12ZinIrContextR20ZinObjectNameFactoryRK19ZinTensorDimensionsRKNSt3__113unordered_setI14ZinIrDimensionNS7_4hashIS9_EENS7_8equal_toIS9_EENS7_9allocatorIS9_EEEEfl()');
  },

  onLeave(log, retval, state) {
  }
});
