/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN10ZinBuilder10CreateSortEP12ZinIrContextR20ZinObjectNameFactoryRK19ZinTensorDimensions15ZinTensorFormat18ZinIrSortDirection14ZinIrDimensionS9_RKNSt3__13setImNSA_4lessImEENSA_9allocatorImEEEEb.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN10ZinBuilder10CreateSortEP12ZinIrContextR20ZinObjectNameFactoryRK19ZinTensorDimensions15ZinTensorFormat18ZinIrSortDirection14ZinIrDimensionS9_RKNSt3__13setImNSA_4lessImEENSA_9allocatorImEEEEb()');
  },

  onLeave(log, retval, state) {
  }
});
