/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN21ZinMirSpatialSplitter19SaveResetOuputLayerER8SubgraphPK12ZinIrOpLayer.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN21ZinMirSpatialSplitter19SaveResetOuputLayerER8SubgraphPK12ZinIrOpLayer()');
  },

  onLeave(log, retval, state) {
  }
});
