/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN21ZinIrOpLayerGraphUtil18GetLayersWithNamesEP17ZinIrOpLayerGraphRKNSt3__16vectorINS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS7_IS9_EEEERNS2_3setIP12ZinIrOpLayerNS2_4lessISG_EENS7_ISG_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN21ZinIrOpLayerGraphUtil18GetLayersWithNamesEP17ZinIrOpLayerGraphRKNSt3__16vectorINS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS7_IS9_EEEERNS2_3setIP12ZinIrOpLayerNS2_4lessISG_EENS7_ISG_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
