/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN23ZinCpBasedAllocatorUtil22PrintRegionInformationERNSt3__114basic_ofstreamIcNS0_11char_traitsIcEEEERKNS0_6vectorINS6_IPK14ZinEngineLayerNS0_9allocatorIS9_EEEENSA_ISC_EEEERKNS0_3setIP11ZinIrTensor15ZinIrComparatorISI_ENSA_ISJ_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN23ZinCpBasedAllocatorUtil22PrintRegionInformationERNSt3__114basic_ofstreamIcNS0_11char_traitsIcEEEERKNS0_6vectorINS6_IPK14ZinEngineLayerNS0_9allocatorIS9_EEEENSA_ISC_EEEERKNS0_3setIP11ZinIrTensor15ZinIrComparatorISI_ENSA_ISJ_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
