/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN22ZinLayerNormLayerUtils27DecomposeLayerNormalizationERKNSt3__113unordered_setI14ZinIrDimensionNS0_4hashIS2_EENS0_8equal_toIS2_EENS0_9allocatorIS2_EEEERK19ZinTensorDimensionsRNS0_6vectorINS_23LayerNormDecomposedDescENS7_ISG_EEEERNSF_ISC_NS7_ISC_EEEEl.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN22ZinLayerNormLayerUtils27DecomposeLayerNormalizationERKNSt3__113unordered_setI14ZinIrDimensionNS0_4hashIS2_EENS0_8equal_toIS2_EENS0_9allocatorIS2_EEEERK19ZinTensorDimensionsRNS0_6vectorINS_23LayerNormDecomposedDescENS7_ISG_EEEERNSF_ISC_NS7_ISC_EEEEl()');
  },

  onLeave(log, retval, state) {
  }
});
