/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN35PressureBasedSubgraphIdentification17ReclusterSubgraphERK8SubgraphRNSt3__16vectorINS3_3setIP12ZinIrOpLayerNS3_4lessIS7_EENS3_9allocatorIS7_EEEENSA_ISC_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN35PressureBasedSubgraphIdentification17ReclusterSubgraphERK8SubgraphRNSt3__16vectorINS3_3setIP12ZinIrOpLayerNS3_4lessIS7_EENS3_9allocatorIS7_EEEENSA_ISC_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
