/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN35PressureBasedSubgraphIdentification18ConstructSubGraphsERNSt3__16vectorINS0_3setIP12ZinIrOpLayerNS0_4lessIS4_EENS0_9allocatorIS4_EEEENS7_IS9_EEEERKNS0_13unordered_mapIPK11ZinIrTensorN12CpAllocUtils14AllocationTypeENS0_4hashISG_EENS0_8equal_toISG_EENS7_INS0_4pairIKSG_SI_EEEEEERNS1_I8SubgraphNS7_ISU_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN35PressureBasedSubgraphIdentification18ConstructSubGraphsERNSt3__16vectorINS0_3setIP12ZinIrOpLayerNS0_4lessIS4_EENS0_9allocatorIS4_EEEENS7_IS9_EEEERKNS0_13unordered_mapIPK11ZinIrTensorN12CpAllocUtils14AllocationTypeENS0_4hashISG_EENS0_8equal_toISG_EENS7_INS0_4pairIKSG_SI_EEEEEERNS1_I8SubgraphNS7_ISU_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
