/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN35PressureBasedSubgraphIdentification24IdentifyInputOutputNodesERKNSt3__13setIP12ZinIrOpLayerNS0_4lessIS3_EENS0_9allocatorIS3_EEEER8Subgraph.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN35PressureBasedSubgraphIdentification24IdentifyInputOutputNodesERKNSt3__13setIP12ZinIrOpLayerNS0_4lessIS3_EENS0_9allocatorIS3_EEEER8Subgraph()');
  },

  onLeave(log, retval, state) {
  }
});
