/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN8ZinIrOpt16TransposeMatmultC2EP17ZinIrOpLayerGraphRK15ZinIrParametersRKNSt3__110shared_ptrI10ZinPatternEERNS6_13unordered_setIP12ZinIrOpLayerNS6_4hashISE_EENS6_8equal_toISE_EENS6_9allocatorISE_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN8ZinIrOpt16TransposeMatmultC2EP17ZinIrOpLayerGraphRK15ZinIrParametersRKNSt3__110shared_ptrI10ZinPatternEERNS6_13unordered_setIP12ZinIrOpLayerNS6_4hashISE_EENS6_8equal_toISE_EENS6_9allocatorISE_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
