/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK14ZinMirL2Config18HasL2DependentModeE18ZinL2DependentModeRNSt3__13setI12ZinL2SrcTypeNS1_4lessIS3_EENS1_9allocatorIS3_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK14ZinMirL2Config18HasL2DependentModeE18ZinL2DependentModeRNSt3__13setI12ZinL2SrcTypeNS1_4lessIS3_EENS1_9allocatorIS3_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
