/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK12CpAllocGraph15GetInPlacePortsEmRNSt3__13setImNS0_4lessImEENS0_9allocatorImEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK12CpAllocGraph15GetInPlacePortsEmRNSt3__13setImNS0_4lessImEENS0_9allocatorImEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
