/*
 * Auto-generated by Frida. Please modify to match the signature of $s14FamilyCircleUI06SimpleA11ServerCacheC3set_5valueyAA0aF3KeyV_So8NSObjectCtFTj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s14FamilyCircleUI06SimpleA11ServerCacheC3set_5valueyAA0aF3KeyV_So8NSObjectCtFTj()');
  },

  onLeave(log, retval, state) {
  }
});
