/*
 * Auto-generated by Frida. Please modify to match the signature of $s18_JetEngine_SwiftUI29IndexedRandomAccessCollectionVy5IndexQz6offset_7ElementQz7elementtAEcig.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s18_JetEngine_SwiftUI29IndexedRandomAccessCollectionVy5IndexQz6offset_7ElementQz7elementtAEcig()');
  },

  onLeave(log, retval, state) {
  }
});
