/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3ctu4rest15AssertionHandle15setHandler_implEONSt3__18functionIFvbEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN3ctu4rest15AssertionHandle15setHandler_implEONSt3__18functionIFvbEEE()');
  },

  onLeave(log, retval, state) {
  }
});
