/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK3ctu10LoggerBaseINS_14DummyLogServerEE7enabledENS_8LogLevelE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK3ctu10LoggerBaseINS_14DummyLogServerEE7enabledENS_8LogLevelE()');
  },

  onLeave(log, retval, state) {
  }
});
