/*
 * Auto-generated by Frida. Please modify to match the signature of $s12AVFoundation22AVPartialAsyncPropertyCAASo17AVFragmentedAssetCRbzlE6tracksAA07AVAsyncD0CyxSaySo0eF5TrackCGGvgZ.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s12AVFoundation22AVPartialAsyncPropertyCAASo17AVFragmentedAssetCRbzlE6tracksAA07AVAsyncD0CyxSaySo0eF5TrackCGGvgZ()');
  },

  onLeave(log, retval, state) {
  }
});
