/*
 * Auto-generated by Frida. Please modify to match the signature of $s12AVFoundation22AVPartialAsyncPropertyCAASo7AVAssetCRbzlE32providesPreciseDurationAndTimingAA07AVAsyncD0CyxSbGvgZ.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s12AVFoundation22AVPartialAsyncPropertyCAASo7AVAssetCRbzlE32providesPreciseDurationAndTimingAA07AVAsyncD0CyxSbGvgZ()');
  },

  onLeave(log, retval, state) {
  }
});
