/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo29AVAssetVariantVideoAttributesC12AVFoundationE10codecTypesSays6UInt32VGvg.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo29AVAssetVariantVideoAttributesC12AVFoundationE10codecTypesSays6UInt32VGvg()');
  },

  onLeave(log, retval, state) {
  }
});
