/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN4pugi8xml_node9set_valueEPKc.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN4pugi8xml_node9set_valueEPKc()');
  },

  onLeave(log, retval, state) {
  }
});
