/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN4pugi18xpath_variable_set8_destroyEPNS_14xpath_variableE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN4pugi18xpath_variable_set8_destroyEPNS_14xpath_variableE()');
  },

  onLeave(log, retval, state) {
  }
});
