/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN11flatbuffers14DeserializeDocERNSt3__16vectorINS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS5_IS7_EEEEPKNS_6VectorINS_6OffsetINS_6StringEEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN11flatbuffers14DeserializeDocERNSt3__16vectorINS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS5_IS7_EEEEPKNS_6VectorINS_6OffsetINS_6StringEEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
