/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3MIL11IRParameter4MakeENSt3__110shared_ptrINS1_13unordered_setIPKNS_11IRValueTypeENS1_4hashIS6_EENS1_8equal_toIS6_EENS1_9allocatorIS6_EEEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN3MIL11IRParameter4MakeENSt3__110shared_ptrINS1_13unordered_setIPKNS_11IRValueTypeENS1_4hashIS6_EENS1_8equal_toIS6_EENS1_9allocatorIS6_EEEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
