/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK3MIL6Opsets6Common5ios1510ios15Opset7GetNameEv.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK3MIL6Opsets6Common5ios1510ios15Opset7GetNameEv()');
  },

  onLeave(log, retval, state) {
  }
});
