/*
 * Auto-generated by Frida. Please modify to match the signature of $s13SharedWithYou30_SWCollaborationButtonViewImplC09setManageE5Title06manageeJ0ySS_tF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s13SharedWithYou30_SWCollaborationButtonViewImplC09setManageE5Title06manageeJ0ySS_tF()');
  },

  onLeave(log, retval, state) {
  }
});
