/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3cva3adp2io15PListSerializer7setItemIiEEbRKNSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEESC_RKT_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN3cva3adp2io15PListSerializer7setItemIiEEbRKNSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEESC_RKT_()');
  },

  onLeave(log, retval, state) {
  }
});
