/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3cva6Logger9setTargetENSt3__110shared_ptrINS0_6TargetEEEPKc.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN3cva6Logger9setTargetENSt3__110shared_ptrINS0_6TargetEEEPKc()');
  },

  onLeave(log, retval, state) {
  }
});
