/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK3cva14ProgramOptions11Description21set_default_argumentsERNSt3__13mapINS0_3KeyENS2_6vectorINS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS9_ISB_EEEENS2_4lessIS4_EENS9_INS2_4pairIKS4_SD_EEEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK3cva14ProgramOptions11Description21set_default_argumentsERNSt3__13mapINS0_3KeyENS2_6vectorINS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS9_ISB_EEEENS2_4lessIS4_EENS9_INS2_4pairIKS4_SD_EEEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
