/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN6mlcore14AnyInPredicateINSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEEC1ERKNS1_6vectorIPNS_13ModelPropertyIS7_EENS5_ISC_EEEENS_12SharedObjectINS1_13unordered_setIS7_NS1_4hashIS7_EENS1_8equal_toIS7_EENS5_IS7_EEEEiEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN6mlcore14AnyInPredicateINSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEEC1ERKNS1_6vectorIPNS_13ModelPropertyIS7_EENS5_ISC_EEEENS_12SharedObjectINS1_13unordered_setIS7_NS1_4hashIS7_EENS1_8equal_toIS7_EENS5_IS7_EEEEiEE()');
  },

  onLeave(log, retval, state) {
  }
});
