/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN6mlcore14AnyInPredicateIN13mediaplatform4DataEEC1ERKNSt3__16vectorIPNS_13ModelPropertyIS2_EENS4_9allocatorIS8_EEEENS_12SharedObjectINS4_13unordered_setIS2_NS4_4hashIS2_EENS4_8equal_toIS2_EENS9_IS2_EEEEiEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN6mlcore14AnyInPredicateIN13mediaplatform4DataEEC1ERKNSt3__16vectorIPNS_13ModelPropertyIS2_EENS4_9allocatorIS8_EEEENS_12SharedObjectINS4_13unordered_setIS2_NS4_4hashIS2_EENS4_8equal_toIS2_EENS9_IS2_EEEEiEE()');
  },

  onLeave(log, retval, state) {
  }
});
