/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN6mlcore11InPredicateIdEC1EPNS_13ModelPropertyIdEERKNS_12SharedObjectINSt3__113unordered_setIdNS6_4hashIdEENS6_8equal_toIdEENS6_9allocatorIdEEEEiEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN6mlcore11InPredicateIdEC1EPNS_13ModelPropertyIdEERKNS_12SharedObjectINSt3__113unordered_setIdNS6_4hashIdEENS6_8equal_toIdEENS6_9allocatorIdEEEEiEE()');
  },

  onLeave(log, retval, state) {
  }
});
