/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN6mlcore16MultiEntityQuery23setMultiSortDescriptorsERKNSt3__16vectorINS_19MultiSortDescriptorENS1_9allocatorIS3_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN6mlcore16MultiEntityQuery23setMultiSortDescriptorsERKNSt3__16vectorINS_19MultiSortDescriptorENS1_9allocatorIS3_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
