/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN6mlcore20LocalizedSearchQuery9setScopesERKNSt3__16vectorINS1_10shared_ptrINS_20LocalizedSearchScopeEEENS1_9allocatorIS5_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN6mlcore20LocalizedSearchQuery9setScopesERKNSt3__16vectorINS1_10shared_ptrINS_20LocalizedSearchScopeEEENS1_9allocatorIS5_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
