/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN6mlcore11InPredicateIiEC1EPNS_13ModelPropertyIiEERKNSt3__113unordered_setIiNS5_4hashIiEENS5_8equal_toIiEENS5_9allocatorIiEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN6mlcore11InPredicateIiEC1EPNS_13ModelPropertyIiEERKNSt3__113unordered_setIiNS5_4hashIiEENS5_8equal_toIiEENS5_9allocatorIiEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
