/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN6mlcore11InPredicateIN13mediaplatform4DataEEC1EPNS_13ModelPropertyIS2_EERKNS_12SharedObjectINSt3__113unordered_setIS2_NS8_4hashIS2_EENS8_8equal_toIS2_EENS8_9allocatorIS2_EEEEiEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN6mlcore11InPredicateIN13mediaplatform4DataEEC1EPNS_13ModelPropertyIS2_EERKNS_12SharedObjectINSt3__113unordered_setIS2_NS8_4hashIS2_EENS8_8equal_toIS2_EENS8_9allocatorIS2_EEEEiEE()');
  },

  onLeave(log, retval, state) {
  }
});
