/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK6mlcore14ItemStoreTable39assetStoreExtendedLyricsAttributeColumnEv.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK6mlcore14ItemStoreTable39assetStoreExtendedLyricsAttributeColumnEv()');
  },

  onLeave(log, retval, state) {
  }
});
