/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo26MKGradientPolylineRendererC6MapKitE9setColors_9locationsySaySo7UIColorCG_Say12CoreGraphics7CGFloatVGtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo26MKGradientPolylineRendererC6MapKitE9setColors_9locationsySaySo7UIColorCG_Say12CoreGraphics7CGFloatVGtF()');
  },

  onLeave(log, retval, state) {
  }
});
