/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN13IlmThread_2_310ThreadPool17setThreadProviderEPNS_18ThreadPoolProviderE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN13IlmThread_2_310ThreadPool17setThreadProviderEPNS_18ThreadPoolProviderE()');
  },

  onLeave(log, retval, state) {
  }
});
