/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7Alembic3Abc3v118IArchive26setReadArraySampleCachePtrENSt3__110shared_ptrINS_15AbcCoreAbstract3v1120ReadArraySampleCacheEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7Alembic3Abc3v118IArchive26setReadArraySampleCachePtrENSt3__110shared_ptrINS_15AbcCoreAbstract3v1120ReadArraySampleCacheEEE()');
  },

  onLeave(log, retval, state) {
  }
});
