/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7Alembic7AbcGeom3v1111XformSample9setMatrixERKN9Imath_2_38Matrix44IdEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7Alembic7AbcGeom3v1111XformSample9setMatrixERKN9Imath_2_38Matrix44IdEE()');
  },

  onLeave(log, retval, state) {
  }
});
