/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7Alembic7AbcGeom3v117XformOp7setAxisERKN9Imath_2_34Vec3IdEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7Alembic7AbcGeom3v117XformOp7setAxisERKN9Imath_2_34Vec3IdEE()');
  },

  onLeave(log, retval, state) {
  }
});
