/*
 * Auto-generated by Frida. Please modify to match the signature of $s21InternalSwiftProtobuf17ExtensibleMessagePAAE17setExtensionValue3ext5valueyAA0eG0CyAA013RepeatedGroupG5FieldVyqd__GxG_Sayqd__GtAA0E0Rd__SHRd__lF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s21InternalSwiftProtobuf17ExtensibleMessagePAAE17setExtensionValue3ext5valueyAA0eG0CyAA013RepeatedGroupG5FieldVyqd__GxG_Sayqd__GtAA0E0Rd__SHRd__lF()');
  },

  onLeave(log, retval, state) {
  }
});
