/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo26MDLAnimatedQuaternionArrayC7ModelIOE5reset06doublebC07atTimesySaySo10simd_quatdaG_SaySdGtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo26MDLAnimatedQuaternionArrayC7ModelIOE5reset06doublebC07atTimesySaySo10simd_quatdaG_SaySdGtF()');
  },

  onLeave(log, retval, state) {
  }
});
