/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo23MDLAnimatedVector3ArrayC7ModelIOE3set07double3C06atTimeySays5SIMD3VySdGG_SdtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo23MDLAnimatedVector3ArrayC7ModelIOE3set07double3C06atTimeySays5SIMD3VySdGG_SdtF()');
  },

  onLeave(log, retval, state) {
  }
});
