/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo21MDLAnimatedQuaternionC7ModelIOE5reset06doubleB5Array7atTimesySaySo10simd_quatdaG_SaySdGtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo21MDLAnimatedQuaternionC7ModelIOE5reset06doubleB5Array7atTimesySaySo10simd_quatdaG_SaySdGtF()');
  },

  onLeave(log, retval, state) {
  }
});
