/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo22MDLAnimatedScalarArrayC7ModelIOE5reset05floatC07atTimesySaySfG_SaySdGtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo22MDLAnimatedScalarArrayC7ModelIOE5reset05floatC07atTimesySaySfG_SaySdGtF()');
  },

  onLeave(log, retval, state) {
  }
});
