/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo20MDLAnimatedMatrix4x4C7ModelIOE5reset13float4x4Array7atTimesySaySo05simd_F0aG_SaySdGtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo20MDLAnimatedMatrix4x4C7ModelIOE5reset13float4x4Array7atTimesySaySo05simd_F0aG_SaySdGtF()');
  },

  onLeave(log, retval, state) {
  }
});
