/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo26MDLAnimatedQuaternionArrayC7ModelIOE3set05floatbC06atTimeySaySo10simd_quatfaG_SdtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo26MDLAnimatedQuaternionArrayC7ModelIOE3set05floatbC06atTimeySaySo10simd_quatfaG_SdtF()');
  },

  onLeave(log, retval, state) {
  }
});
