/*
 * Auto-generated by Frida. Please modify to match the signature of $s10Accelerate4vDSPO18VectorizableDoubleV11applySingle6source11destination6delays5setup12sectionCount5countyx_q_zSpySdGs13OpaquePointerVS2utAA0A6BufferRzAA0a7MutableP0R_Sd7ElementRtzSdARRt_r0_lFZ.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s10Accelerate4vDSPO18VectorizableDoubleV11applySingle6source11destination6delays5setup12sectionCount5countyx_q_zSpySdGs13OpaquePointerVS2utAA0A6BufferRzAA0a7MutableP0R_Sd7ElementRtzSdARRt_r0_lFZ()');
  },

  onLeave(log, retval, state) {
  }
});
