/*
 * Auto-generated by Frida. Please modify to match the signature of $s10Accelerate4vDSPO18VectorizableDoubleV10applyMulti5setup7pInputs8pOutputs5countys13OpaquePointerV_SpySPySdGGSpySpySdGGSutFZ.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s10Accelerate4vDSPO18VectorizableDoubleV10applyMulti5setup7pInputs8pOutputs5countys13OpaquePointerV_SpySPySdGGSpySpySdGGSutFZ()');
  },

  onLeave(log, retval, state) {
  }
});
