/*
 * Auto-generated by Frida. Please modify to match the signature of $s10Accelerate20vDSP_BiquadFunctionsP11applySingle6source11destination6delays5setup12sectionCount5countyqd___qd_0_zSpy6ScalarQzGs13OpaquePointerVS2utAA0A6BufferRd__AA0a7MutableQ0Rd_0_7ElementQyd__ALRSARQyd_0_ASRSr0_lFZTj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s10Accelerate20vDSP_BiquadFunctionsP11applySingle6source11destination6delays5setup12sectionCount5countyqd___qd_0_zSpy6ScalarQzGs13OpaquePointerVS2utAA0A6BufferRd__AA0a7MutableQ0Rd_0_7ElementQyd__ALRSARQyd_0_ASRSr0_lFZTj()');
  },

  onLeave(log, retval, state) {
  }
});
