/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo14BNNSActivationa10AccelerateE21integerLinearSaturate5scale6offset5shiftABs5Int32V_A2ItFZ.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo14BNNSActivationa10AccelerateE21integerLinearSaturate5scale6offset5shiftABs5Int32V_A2ItFZ()');
  },

  onLeave(log, retval, state) {
  }
});
