/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo14BNNSActivationa10AccelerateE31integerLinearSaturatePerChannel5scale6offset5shiftABSPys5Int32VG_A2JtFZ.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo14BNNSActivationa10AccelerateE31integerLinearSaturatePerChannel5scale6offset5shiftABSPys5Int32VG_A2JtFZ()');
  },

  onLeave(log, retval, state) {
  }
});
