/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN17jet_context_Metal17set_vertex_bufferEP10jet_bufferi.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN17jet_context_Metal17set_vertex_bufferEP10jet_bufferi()');
  },

  onLeave(log, retval, state) {
  }
});
