/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN11jet_context17set_vertex_bufferERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEP10jet_buffer.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN11jet_context17set_vertex_bufferERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEP10jet_buffer()');
  },

  onLeave(log, retval, state) {
  }
});
