/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN11jet_context25set_vertex_constant_valueERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEDv4_f.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN11jet_context25set_vertex_constant_valueERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEDv4_f()');
  },

  onLeave(log, retval, state) {
  }
});
