/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN18jet_context_OpenGL27set_stencil_reference_valueEj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN18jet_context_OpenGL27set_stencil_reference_valueEj()');
  },

  onLeave(log, retval, state) {
  }
});
