/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN13mediaplatform21DatabaseIndexedColumn14setCollateTypeENS_15SQLOrderingTerm11CollateTypeE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN13mediaplatform21DatabaseIndexedColumn14setCollateTypeENS_15SQLOrderingTerm11CollateTypeE()');
  },

  onLeave(log, retval, state) {
  }
});
