/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN13mediaplatform16DatabaseFunction11setCallbackERKNSt3__18functionIFvNS_15DatabaseContextERNS1_6vectorINS_13DatabaseValueENS1_9allocatorIS5_EEEEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN13mediaplatform16DatabaseFunction11setCallbackERKNSt3__18functionIFvNS_15DatabaseContextERNS1_6vectorINS_13DatabaseValueENS1_9allocatorIS5_EEEEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
