/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN13mediaplatform15DatabaseContext9setResultINSt3__112basic_stringIwNS2_11char_traitsIwEENS2_9allocatorIwEEEEEEvRKT_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN13mediaplatform15DatabaseContext9setResultINSt3__112basic_stringIwNS2_11char_traitsIwEENS2_9allocatorIwEEEEEEvRKT_()');
  },

  onLeave(log, retval, state) {
  }
});
