/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN13mediaplatform22SQLSelectCoreStatement16setResultColumnsERKNSt3__16vectorINS1_10shared_ptrIKNS_13SQLExpressionEEENS1_9allocatorIS6_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN13mediaplatform22SQLSelectCoreStatement16setResultColumnsERKNSt3__16vectorINS1_10shared_ptrIKNS_13SQLExpressionEEENS1_9allocatorIS6_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
