/*
 * Auto-generated by Frida. Please modify to match the signature of sec_protocol_options_set_tls_encryption_secret_update_block.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('sec_protocol_options_set_tls_encryption_secret_update_block()');
  },

  onLeave(log, retval, state) {
  }
});
