/*
 * Auto-generated by Frida. Please modify to match the signature of $s16DriverManagement0A7ManagerC03setA5State_8approvedyAA0a8ApprovalE0C_SbtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s16DriverManagement0A7ManagerC03setA5State_8approvedyAA0a8ApprovalE0C_SbtF()');
  },

  onLeave(log, retval, state) {
  }
});
