/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN13EspressoLight17espresso_aot_plan12set_platformEjj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN13EspressoLight17espresso_aot_plan12set_platformEjj()');
  },

  onLeave(log, retval, state) {
  }
});
