/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN13EspressoLight17espresso_aot_plan26set_ane_options_plist_pathENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN13EspressoLight17espresso_aot_plan26set_ane_options_plist_pathENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
