/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN13EspressoLight22abstract_espresso_plan24bind_input_cvpixelbufferEiPKciP10__CVBufferP11objc_objectiP44espresso_simple_image_preprocessing_params_tP25espresso_scaling_settingsbb.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN13EspressoLight22abstract_espresso_plan24bind_input_cvpixelbufferEiPKciP10__CVBufferP11objc_objectiP44espresso_simple_image_preprocessing_params_tP25espresso_scaling_settingsbb()');
  },

  onLeave(log, retval, state) {
  }
});
