/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN8Espresso17dataset_estimator39sample_stats_with_current_network_stateERKNS0_9options_tE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN8Espresso17dataset_estimator39sample_stats_with_current_network_stateERKNS0_9options_tE()');
  },

  onLeave(log, retval, state) {
  }
});
