/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN8Espresso11base_kernel18set_parameter_blobENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEOKNS_8blob_cpuE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN8Espresso11base_kernel18set_parameter_blobENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEOKNS_8blob_cpuE()');
  },

  onLeave(log, retval, state) {
  }
});
