/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN8Espresso33generic_dynamic_dequantize_kernel21__set_weight_raw_blobERKNSt3__110shared_ptrINS_14abstract_batchEEERKNS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPvmPNS_11base_kernel18set_weight_optionsE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN8Espresso33generic_dynamic_dequantize_kernel21__set_weight_raw_blobERKNSt3__110shared_ptrINS_14abstract_batchEEERKNS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPvmPNS_11base_kernel18set_weight_optionsE()');
  },

  onLeave(log, retval, state) {
  }
});
