/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN8Espresso32set_conv_quantized_weight_helperERKNSt3__110shared_ptrINS_14abstract_batchEEERKNS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEPvmPNS_11base_kernel18set_weight_optionsERNS1_INS_24quantized_weights_helperEEERKNS_11layer_shapeENS1_INS_16abstract_contextEEENSI_17QUANTIZATION_AXISEb.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN8Espresso32set_conv_quantized_weight_helperERKNSt3__110shared_ptrINS_14abstract_batchEEERKNS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEPvmPNS_11base_kernel18set_weight_optionsERNS1_INS_24quantized_weights_helperEEERKNS_11layer_shapeENS1_INS_16abstract_contextEEENSI_17QUANTIZATION_AXISEb()');
  },

  onLeave(log, retval, state) {
  }
});
