/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN8Espresso14abstract_batch17setup_for_networkERNS_3netE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN8Espresso14abstract_batch17setup_for_networkERNS_3netE()');
  },

  onLeave(log, retval, state) {
  }
});
