/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN8Espresso17dataset_estimator18statistics_entry_t26iterative_grow_with_scalarEfb.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN8Espresso17dataset_estimator18statistics_entry_t26iterative_grow_with_scalarEfb()');
  },

  onLeave(log, retval, state) {
  }
});
