/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN8Espresso20transform_dequantizeENSt3__110shared_ptrINS_3netEEERKNS0_13unordered_setINS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS0_4hashISA_EENS0_8equal_toISA_EENS8_ISA_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN8Espresso20transform_dequantizeENSt3__110shared_ptrINS_3netEEERKNS0_13unordered_setINS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS0_4hashISA_EENS0_8equal_toISA_EENS8_ISA_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
