/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN8Espresso8blob_cpu16set_reference_toERKNSt3__110shared_ptrINS_23abstract_blob_containerEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN8Espresso8blob_cpu16set_reference_toERKNSt3__110shared_ptrINS_23abstract_blob_containerEEE()');
  },

  onLeave(log, retval, state) {
  }
});
