/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN8Espresso11base_kernel18set_parameter_blobItLi5EEEvNSt3__110shared_ptrINS_16abstract_contextEEENS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS3_INS_4blobIT_XT0_EEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN8Espresso11base_kernel18set_parameter_blobItLi5EEEvNSt3__110shared_ptrINS_16abstract_contextEEENS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS3_INS_4blobIT_XT0_EEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
