/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN8Espresso24quantized_weights_helper22__set_weights_finalizeERKNSt3__110shared_ptrINS_14abstract_batchEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN8Espresso24quantized_weights_helper22__set_weights_finalizeERKNSt3__110shared_ptrINS_14abstract_batchEEE()');
  },

  onLeave(log, retval, state) {
  }
});
