/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN8Espresso3AOT18AOTCompilerOptions11UnsetOptionERKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEESA_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN8Espresso3AOT18AOTCompilerOptions11UnsetOptionERKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEESA_()');
  },

  onLeave(log, retval, state) {
  }
});
