/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN8Espresso13interpreter_t32setup_fix_context_transfer_racesEv.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN8Espresso13interpreter_t32setup_fix_context_transfer_racesEv()');
  },

  onLeave(log, retval, state) {
  }
});
