/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN8Espresso13interpreter_t5setupENSt3__110shared_ptrINS_3netEEENS_12compute_pathENS2_INS_6SerDes21generic_serdes_objectEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN8Espresso13interpreter_t5setupENSt3__110shared_ptrINS_3netEEENS_12compute_pathENS2_INS_6SerDes21generic_serdes_objectEEE()');
  },

  onLeave(log, retval, state) {
  }
});
