/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN8Espresso3net20set_metadata_for_keyERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS_11layer_shapeENS1_10shared_ptrINS_4blobIfLi5EEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN8Espresso3net20set_metadata_for_keyERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS_11layer_shapeENS1_10shared_ptrINS_4blobIfLi5EEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
