/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN8Espresso12brick_kernel15set_weight_blobERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPKvm.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN8Espresso12brick_kernel15set_weight_blobERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPKvm()');
  },

  onLeave(log, retval, state) {
  }
});
