/*
 * Auto-generated by Frida. Please modify to match the signature of e5rt_tensor_utils_set_s8_element.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('e5rt_tensor_utils_set_s8_element()');
  },

  onLeave(log, retval, state) {
  }
});
