/*
 * Auto-generated by Frida. Please modify to match the signature of espresso_set_mil_const_values.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('espresso_set_mil_const_values()');
  },

  onLeave(log, retval, state) {
  }
});
