/*
 * Auto-generated by Frida. Please modify to match the signature of $s7TipKit20A22CollectionReusableViewC3setyACyxGXDs24ReferenceWritableKeyPathCyAA0a7HostingE0CyxGqd__G_qd__tlFTj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s7TipKit20A22CollectionReusableViewC3setyACyxGXDs24ReferenceWritableKeyPathCyAA0a7HostingE0CyxGqd__G_qd__tlFTj()');
  },

  onLeave(log, retval, state) {
  }
});
