/*
 * Auto-generated by Frida. Please modify to match the signature of $s7TipKit20A9ViewModelC11$edgeInsets7Combine9PublishedV9PublisherVy7SwiftUI04EdgeF0V_GvMTj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s7TipKit20A9ViewModelC11$edgeInsets7Combine9PublishedV9PublisherVy7SwiftUI04EdgeF0V_GvMTj()');
  },

  onLeave(log, retval, state) {
  }
});
