/*
 * Auto-generated by Frida. Please modify to match the signature of wifi_manager_set_network_property.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('wifi_manager_set_network_property()');
  },

  onLeave(log, retval, state) {
  }
});
