/*
 * Auto-generated by Frida. Please modify to match the signature of brc_notify_set_state_and_post.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('brc_notify_set_state_and_post()');
  },

  onLeave(log, retval, state) {
  }
});
