/*
 * Auto-generated by Frida. Please modify to match the signature of _Z22acl_compare_permset_npP12_acl_permsetS0_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_Z22acl_compare_permset_npP12_acl_permsetS0_()');
  },

  onLeave(log, retval, state) {
  }
});
