/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN18TDeepCFURLIteratorC2ERKNSt3__110shared_ptrI10TCFURLInfoEEbbPK9__CFArraybPNS0_13unordered_setIyNS0_4hashIyEENS0_8equal_toIyEENS0_9allocatorIyEEEEP11TCloneCacheP17TReservationStackbbbbS3_NS2_17CopyOperationKindE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN18TDeepCFURLIteratorC2ERKNSt3__110shared_ptrI10TCFURLInfoEEbbPK9__CFArraybPNS0_13unordered_setIyNS0_4hashIyEENS0_8equal_toIyEENS0_9allocatorIyEEEEP11TCloneCacheP17TReservationStackbbbbS3_NS2_17CopyOperationKindE()');
  },

  onLeave(log, retval, state) {
  }
});
