/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7TFSInfo30SynchonizeFPProviderPropertiesERKNSt3__110shared_ptrIS_EERNS0_3setI8PropertyNS0_4lessIS6_EENS0_9allocatorIS6_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7TFSInfo30SynchonizeFPProviderPropertiesERKNSt3__110shared_ptrIS_EERNS0_3setI8PropertyNS0_4lessIS6_EENS0_9allocatorIS6_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
