/*
 * Auto-generated by Frida. Please modify to match the signature of log_set_level.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('log_set_level()');
  },

  onLeave(log, retval, state) {
  }
});
