/*
 * Auto-generated by Frida. Please modify to match the signature of $s6TipKit18TPKBaseContentViewC28defaultDirectionalEdgeInsetsSo013NSDirectionalhI0VvM.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s6TipKit18TPKBaseContentViewC28defaultDirectionalEdgeInsetsSo013NSDirectionalhI0VvM()');
  },

  onLeave(log, retval, state) {
  }
});
