/*
 * Auto-generated by Frida. Please modify to match the signature of $s6TipKit33TPKTipContentCollectionHeaderViewC03setD0_17contentControlleryAA10TPKContentC_So0kJ0CtFTj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s6TipKit33TPKTipContentCollectionHeaderViewC03setD0_17contentControlleryAA10TPKContentC_So0kJ0CtFTj()');
  },

  onLeave(log, retval, state) {
  }
});
