/*
 * Auto-generated by Frida. Please modify to match the signature of set_first_boot_work_completed.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('set_first_boot_work_completed()');
  },

  onLeave(log, retval, state) {
  }
});
