/*
 * Auto-generated by Frida. Please modify to match the signature of $s9TipsCore25AssetC6encode2toys7Encoder_p_tKF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s9TipsCore25AssetC6encode2toys7Encoder_p_tKF()');
  },

  onLeave(log, retval, state) {
  }
});
