/*
 * Auto-generated by Frida. Please modify to match the signature of $s9TipsCore23TipC2id5title7message5asset7actions5rules7optionsACSS_SayAA14MessageContent_pGyXEAA0K11Convertable_pAA5AssetCSayAA6ActionCGSayAA4RuleCGAA0C7OptionsVtcfC.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s9TipsCore23TipC2id5title7message5asset7actions5rules7optionsACSS_SayAA14MessageContent_pGyXEAA0K11Convertable_pAA5AssetCSayAA6ActionCGSayAA4RuleCGAA0C7OptionsVtcfC()');
  },

  onLeave(log, retval, state) {
  }
});
