/*
 * Auto-generated by Frida. Please modify to match the signature of $s9TipsCore25AssetC4type4data9assetName06bundleG05colorAcA0C4TypeO_10Foundation4DataVSgSSSgAoA14ColorReferenceVSgtcfC.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s9TipsCore25AssetC4type4data9assetName06bundleG05colorAcA0C4TypeO_10Foundation4DataVSgSSSgAoA14ColorReferenceVSgtcfC()');
  },

  onLeave(log, retval, state) {
  }
});
