/*
 * Auto-generated by Frida. Please modify to match the signature of archive_entry_unset_size.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('archive_entry_unset_size()');
  },

  onLeave(log, retval, state) {
  }
});
