/*
 * Auto-generated by Frida. Please modify to match the signature of $s12RTCReporting01_A1SC12setDigestKey_9algorithmSbSo6NSDataC_So0A19EncryptionAlgorithmVtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s12RTCReporting01_A1SC12setDigestKey_9algorithmSbSo6NSDataC_So0A19EncryptionAlgorithmVtF()');
  },

  onLeave(log, retval, state) {
  }
});
