/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3tbb8internal6market22set_active_num_workersEj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN3tbb8internal6market22set_active_num_workersEj()');
  },

  onLeave(log, retval, state) {
  }
});
