/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3tbb21set_assertion_handlerEPFvPKciS1_S1_E.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN3tbb21set_assertion_handlerEPFvPKciS1_S1_E()');
  },

  onLeave(log, retval, state) {
  }
});
