/*
 * Auto-generated by Frida. Please modify to match the signature of $s9JetEngine34AMSMetricsIdentifierFieldsProviderV07accountF07process3bag13shouldMigrate13resetInterval4keysAcA07AccountF0_p_So14AMSProcessInfoCAA3BagVSgSbSdSaySo0cD3KeyCGtcfC.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s9JetEngine34AMSMetricsIdentifierFieldsProviderV07accountF07process3bag13shouldMigrate13resetInterval4keysAcA07AccountF0_p_So14AMSProcessInfoCAA3BagVSgSbSdSaySo0cD3KeyCGtcfC()');
  },

  onLeave(log, retval, state) {
  }
});
