/*
 * Auto-generated by Frida. Please modify to match the signature of $s9JetEngine6ModelsO18HTTPTemplateActionV13SubstitutionsV12setParameter5value3forySS_AE0H0VtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s9JetEngine6ModelsO18HTTPTemplateActionV13SubstitutionsV12setParameter5value3forySS_AE0H0VtF()');
  },

  onLeave(log, retval, state) {
  }
});
