/*
 * Auto-generated by Frida. Please modify to match the signature of $s9JetEngine34AMSMetricsIdentifierFieldsProviderV8accounts10clientInfo13resetInterval4keysAcA8UnstableO8AccountsC_So010AMSProcessI0CSdSaySo0cD3KeyCGtcfC.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s9JetEngine34AMSMetricsIdentifierFieldsProviderV8accounts10clientInfo13resetInterval4keysAcA8UnstableO8AccountsC_So010AMSProcessI0CSdSaySo0cD3KeyCGtcfC()');
  },

  onLeave(log, retval, state) {
  }
});
