/*
 * Auto-generated by Frida. Please modify to match the signature of $s9JetEngine20MetricsFieldsContextV8PropertyVAASdRszlE30metricsIdentifierResetIntervalAEy_SdGvgZ.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s9JetEngine20MetricsFieldsContextV8PropertyVAASdRszlE30metricsIdentifierResetIntervalAEy_SdGvgZ()');
  },

  onLeave(log, retval, state) {
  }
});
