/*
 * Auto-generated by Frida. Please modify to match the signature of $s18AppStoreComponents14ASCLayoutProxyC34adTransparencyButtonScaledCapInset_2in12CoreGraphics7CGFloatVAH_So17UITraitCollectionCtFZ.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s18AppStoreComponents14ASCLayoutProxyC34adTransparencyButtonScaledCapInset_2in12CoreGraphics7CGFloatVAH_So17UITraitCollectionCtFZ()');
  },

  onLeave(log, retval, state) {
  }
});
