/*
 * Auto-generated by Frida. Please modify to match the signature of _Z15pathYyset_debugiPv.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_Z15pathYyset_debugiPv()');
  },

  onLeave(log, retval, state) {
  }
});
