/*
 * Auto-generated by Frida. Please modify to match the signature of _Z16pathYyset_columniPv.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_Z16pathYyset_columniPv()');
  },

  onLeave(log, retval, state) {
  }
});
