/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN38pxrInternal_v0_21__aapl__pxrReserved__8UsdStage9_SetValueIdEENSt3__19enable_ifIXntsr21_IsEditTargetMappableIT_EE5valueEbE4typeENS_11UsdTimeCodeERKNS_12UsdAttributeERKS4_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN38pxrInternal_v0_21__aapl__pxrReserved__8UsdStage9_SetValueIdEENSt3__19enable_ifIXntsr21_IsEditTargetMappableIT_EE5valueEbE4typeENS_11UsdTimeCodeERKNS_12UsdAttributeERKS4_()');
  },

  onLeave(log, retval, state) {
  }
});
