/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN38pxrInternal_v0_21__aapl__pxrReserved__37HdMtlxCreateMtlxDocumentFromHdNetworkERKNS_18HdMaterialNetwork2ERKNS_15HdMaterialNode2ERKNS_7SdfPathERKNSt3__110shared_ptrIN9MaterialX8DocumentEEEPNS9_3setIS6_NS9_4lessIS6_EENS9_9allocatorIS6_EEEEPNS9_13unordered_mapINS9_12basic_stringIcNS9_11char_traitsIcEENSJ_IcEEEESS_NS9_4hashISS_EENS9_8equal_toISS_EENSJ_INS9_4pairIKSS_SS_EEEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN38pxrInternal_v0_21__aapl__pxrReserved__37HdMtlxCreateMtlxDocumentFromHdNetworkERKNS_18HdMaterialNetwork2ERKNS_15HdMaterialNode2ERKNS_7SdfPathERKNSt3__110shared_ptrIN9MaterialX8DocumentEEEPNS9_3setIS6_NS9_4lessIS6_EENS9_9allocatorIS6_EEEEPNS9_13unordered_mapINS9_12basic_stringIcNS9_11char_traitsIcEENSJ_IcEEEESS_NS9_4hashISS_EENS9_8equal_toISS_EENSJ_INS9_4pairIKSS_SS_EEEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
