/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN38pxrInternal_v0_21__aapl__pxrReserved__21ShaderMetadataHelpers27IsPropertyAnAssetIdentifierERKNSt3__113unordered_mapINS_7TfTokenENS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS3_11HashFunctorENS1_8equal_toIS3_EENS7_INS1_4pairIKS3_S9_EEEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN38pxrInternal_v0_21__aapl__pxrReserved__21ShaderMetadataHelpers27IsPropertyAnAssetIdentifierERKNSt3__113unordered_mapINS_7TfTokenENS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS3_11HashFunctorENS1_8equal_toIS3_EENS7_INS1_4pairIKS3_S9_EEEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
