/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN38pxrInternal_v0_21__aapl__pxrReserved__8SdfLayer12ReloadLayersERKNSt3__13setINS_9TfWeakPtrIS0_EENS1_4lessIS4_EENS1_9allocatorIS4_EEEEb.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN38pxrInternal_v0_21__aapl__pxrReserved__8SdfLayer12ReloadLayersERKNSt3__13setINS_9TfWeakPtrIS0_EENS1_4lessIS4_EENS1_9allocatorIS4_EEEEb()');
  },

  onLeave(log, retval, state) {
  }
});
