/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN38pxrInternal_v0_21__aapl__pxrReserved__25Pcp_IndexingOutputManager3MsgEPKNS_12PcpPrimIndexEONSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEERKNS4_3setINS_10PcpNodeRefENS4_4lessISD_EENS8_ISD_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN38pxrInternal_v0_21__aapl__pxrReserved__25Pcp_IndexingOutputManager3MsgEPKNS_12PcpPrimIndexEONSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEERKNS4_3setINS_10PcpNodeRefENS4_4lessISD_EENS8_ISD_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
