/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN38pxrInternal_v0_21__aapl__pxrReserved__10UsdZipFile4OpenERKNSt3__110shared_ptrINS_7ArAssetEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN38pxrInternal_v0_21__aapl__pxrReserved__10UsdZipFile4OpenERKNSt3__110shared_ptrINS_7ArAssetEEE()');
  },

  onLeave(log, retval, state) {
  }
});
