/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN38pxrInternal_v0_21__aapl__pxrReserved__12SdfReferenceC1ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKNS_7SdfPathERKNS_14SdfLayerOffsetERKNS_12VtDictionaryE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN38pxrInternal_v0_21__aapl__pxrReserved__12SdfReferenceC1ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKNS_7SdfPathERKNS_14SdfLayerOffsetERKNS_12VtDictionaryE()');
  },

  onLeave(log, retval, state) {
  }
});
