/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN38pxrInternal_v0_21__aapl__pxrReserved__8UsdStage9_SetValueINS_7VtArrayINSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEEEEENS3_9enable_ifIXntsr21_IsEditTargetMappableIT_EE5valueEbE4typeENS_11UsdTimeCodeERKNS_12UsdAttributeERKSC_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN38pxrInternal_v0_21__aapl__pxrReserved__8UsdStage9_SetValueINS_7VtArrayINSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEEEEENS3_9enable_ifIXntsr21_IsEditTargetMappableIT_EE5valueEbE4typeENS_11UsdTimeCodeERKNS_12UsdAttributeERKSC_()');
  },

  onLeave(log, retval, state) {
  }
});
