/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN38pxrInternal_v0_21__aapl__pxrReserved__13UsdGeomSubset14ValidateFamilyERKNS_16UsdGeomImageableERKNS_7TfTokenES6_PNSt3__112basic_stringIcNS7_11char_traitsIcEENS7_9allocatorIcEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN38pxrInternal_v0_21__aapl__pxrReserved__13UsdGeomSubset14ValidateFamilyERKNS_16UsdGeomImageableERKNS_7TfTokenES6_PNSt3__112basic_stringIcNS7_11char_traitsIcEENS7_9allocatorIcEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
