/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN38pxrInternal_v0_21__aapl__pxrReserved__40Usd_GetAPISchemaPluginApplyToInfoForTypeERKNS_6TfTypeERKNS_7TfTokenEPNSt3__13mapIS3_NS6_6vectorIS3_NS6_9allocatorIS3_EEEENS6_4lessIS3_EENS9_INS6_4pairIS4_SB_EEEEEEPNS_9TfHashMapIS3_SB_NS_6TfHashENS6_8equal_toIS3_EESG_EEPNSJ_IS3_NS6_3setIS3_NS_28TfTokenFastArbitraryLessThanESA_EESK_SM_NS9_INSE_IS4_SR_EEEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN38pxrInternal_v0_21__aapl__pxrReserved__40Usd_GetAPISchemaPluginApplyToInfoForTypeERKNS_6TfTypeERKNS_7TfTokenEPNSt3__13mapIS3_NS6_6vectorIS3_NS6_9allocatorIS3_EEEENS6_4lessIS3_EENS9_INS6_4pairIS4_SB_EEEEEEPNS_9TfHashMapIS3_SB_NS_6TfHashENS6_8equal_toIS3_EESG_EEPNSJ_IS3_NS6_3setIS3_NS_28TfTokenFastArbitraryLessThanESA_EESK_SM_NS9_INSE_IS4_SR_EEEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
