/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN38pxrInternal_v0_21__aapl__pxrReserved__34PcpDynamicFileFormatDependencyData5_Data22_AddRelevantFieldNamesEONSt3__13setINS_7TfTokenENS_28TfTokenFastArbitraryLessThanENS2_9allocatorIS4_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN38pxrInternal_v0_21__aapl__pxrReserved__34PcpDynamicFileFormatDependencyData5_Data22_AddRelevantFieldNamesEONSt3__13setINS_7TfTokenENS_28TfTokenFastArbitraryLessThanENS2_9allocatorIS4_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
