/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN38pxrInternal_v0_21__aapl__pxrReserved__16UsdGeomBBoxCache25ComputeUntransformedBoundERKNS_7UsdPrimERKNSt3__13setINS_7SdfPathENS4_4lessIS6_EENS4_9allocatorIS6_EEEERKNS_9TfHashMapIS6_NS_10GfMatrix4dENS6_4HashENS4_8equal_toIS6_EENS9_INS4_4pairIKS6_SF_EEEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN38pxrInternal_v0_21__aapl__pxrReserved__16UsdGeomBBoxCache25ComputeUntransformedBoundERKNS_7UsdPrimERKNSt3__13setINS_7SdfPathENS4_4lessIS6_EENS4_9allocatorIS6_EEEERKNS_9TfHashMapIS6_NS_10GfMatrix4dENS6_4HashENS4_8equal_toIS6_EENS9_INS4_4pairIKS6_SF_EEEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
