/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK38pxrInternal_v0_21__aapl__pxrReserved__8UsdStage17_DiscoverPayloadsERKNS_7SdfPathENS_13UsdLoadPolicyEPNSt3__13setIS1_NS5_4lessIS1_EENS5_9allocatorIS1_EEEEbSC_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK38pxrInternal_v0_21__aapl__pxrReserved__8UsdStage17_DiscoverPayloadsERKNS_7SdfPathENS_13UsdLoadPolicyEPNSt3__13setIS1_NS5_4lessIS1_EENS5_9allocatorIS1_EEEEbSC_()');
  },

  onLeave(log, retval, state) {
  }
});
