/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK38pxrInternal_v0_21__aapl__pxrReserved__13UsdLuxListAPI14StoreLightListERKNSt3__13setINS_7SdfPathENS1_4lessIS3_EENS1_9allocatorIS3_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK38pxrInternal_v0_21__aapl__pxrReserved__13UsdLuxListAPI14StoreLightListERKNSt3__13setINS_7SdfPathENS1_4lessIS3_EENS1_9allocatorIS3_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
