/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK38pxrInternal_v0_21__aapl__pxrReserved__14UsdShadeShader14GetSourceAssetEPNS_12SdfAssetPathERKNS_7TfTokenE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK38pxrInternal_v0_21__aapl__pxrReserved__14UsdShadeShader14GetSourceAssetEPNS_12SdfAssetPathERKNS_7TfTokenE()');
  },

  onLeave(log, retval, state) {
  }
});
