/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK38pxrInternal_v0_21__aapl__pxrReserved__16UsdCollectionAPI27_ComputeMembershipQueryImplEPNS_28UsdCollectionMembershipQueryERKNSt3__13setINS_7SdfPathENS3_4lessIS5_EENS3_9allocatorIS5_EEEEPb.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK38pxrInternal_v0_21__aapl__pxrReserved__16UsdCollectionAPI27_ComputeMembershipQueryImplEPNS_28UsdCollectionMembershipQueryERKNSt3__13setINS_7SdfPathENS3_4lessIS5_EENS3_9allocatorIS5_EEEEPb()');
  },

  onLeave(log, retval, state) {
  }
});
