/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN14TTSSynthesizer19set_global_propertyENS_14GlobalPropertyEf.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN14TTSSynthesizer19set_global_propertyENS_14GlobalPropertyEf()');
  },

  onLeave(log, retval, state) {
  }
});
