/*
 * Auto-generated by Frida. Please modify to match the signature of $s7SwiftUI4ViewP8SettingsE16settingsIconSizeyQrAD0dfC0V5StyleOF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s7SwiftUI4ViewP8SettingsE16settingsIconSizeyQrAD0dfC0V5StyleOF()');
  },

  onLeave(log, retval, state) {
  }
});
