/*
 * Auto-generated by Frida. Please modify to match the signature of acc_policies_shouldResetLightningBusWhenTransportIsNoLongerRestricted.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('acc_policies_shouldResetLightningBusWhenTransportIsNoLongerRestricted()');
  },

  onLeave(log, retval, state) {
  }
});
