/*
 * Auto-generated by Frida. Please modify to match the signature of $s14SiriTTSService28VocalizerCustomVoiceProviderC4find5voiceAA0E5AssetCSgAA09SynthesisE0C_tFTj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s14SiriTTSService28VocalizerCustomVoiceProviderC4find5voiceAA0E5AssetCSgAA09SynthesisE0C_tFTj()');
  },

  onLeave(log, retval, state) {
  }
});
