/*
 * Auto-generated by Frida. Please modify to match the signature of $s14SiriTTSService18TrialAssetProviderC9findVoiceyAA0gD0CSgAA09SynthesisG0CFTj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s14SiriTTSService18TrialAssetProviderC9findVoiceyAA0gD0CSgAA09SynthesisG0CFTj()');
  },

  onLeave(log, retval, state) {
  }
});
