/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo8TTSAssetC14SiriTTSServiceE3get13serverForTypeSo0A6ServerCSgSo0aG0C_tFZ.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo8TTSAssetC14SiriTTSServiceE3get13serverForTypeSo0A6ServerCSgSo0aG0C_tFZ()');
  },

  onLeave(log, retval, state) {
  }
});
