/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo9OS_os_logC14SiriTTSServiceE8assetXPCABvgZ.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo9OS_os_logC14SiriTTSServiceE8assetXPCABvgZ()');
  },

  onLeave(log, retval, state) {
  }
});
