/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3PAL69get_CoreMedia_kCMSampleBufferAttachmentKey_ResetDecoderBeforeDecodingEv.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN3PAL69get_CoreMedia_kCMSampleBufferAttachmentKey_ResetDecoderBeforeDecodingEv()');
  },

  onLeave(log, retval, state) {
  }
});
