/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN4fido28AuthenticatorGetInfoResponse13setExtensionsEON3WTF6VectorINS1_6StringELm0ENS1_15CrashOnOverflowELm16ENS1_10FastMallocEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN4fido28AuthenticatorGetInfoResponse13setExtensionsEON3WTF6VectorINS1_6StringELm0ENS1_15CrashOnOverflowELm16ENS1_10FastMallocEEE()');
  },

  onLeave(log, retval, state) {
  }
});
