/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7WebCore23RTCRtpSFrameTransformer16setEncryptionKeyERKN3WTF6VectorIhLm0ENS1_15CrashOnOverflowELm16ENS1_10FastMallocEEENSt3__18optionalIyEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7WebCore23RTCRtpSFrameTransformer16setEncryptionKeyERKN3WTF6VectorIhLm0ENS1_15CrashOnOverflowELm16ENS1_10FastMallocEEENSt3__18optionalIyEE()');
  },

  onLeave(log, retval, state) {
  }
});
