/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7WebCore32setAdditionalSupportedImageTypesERKN3WTF6VectorINS0_6StringELm0ENS0_15CrashOnOverflowELm16ENS0_10FastMallocEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7WebCore32setAdditionalSupportedImageTypesERKN3WTF6VectorINS0_6StringELm0ENS0_15CrashOnOverflowELm16ENS0_10FastMallocEEE()');
  },

  onLeave(log, retval, state) {
  }
});
