/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7WebCore24RemoteMediaPlayerSupport31setRegisterRemotePlayerCallbackEON3WTF8FunctionIFvPFvONSt3__110unique_ptrINS_18MediaPlayerFactoryENS3_14default_deleteIS5_EEEEENS_16MediaPlayerEnums21MediaEngineIdentifierEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7WebCore24RemoteMediaPlayerSupport31setRegisterRemotePlayerCallbackEON3WTF8FunctionIFvPFvONSt3__110unique_ptrINS_18MediaPlayerFactoryENS3_14default_deleteIS5_EEEEENS_16MediaPlayerEnums21MediaEngineIdentifierEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
