/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7WebCore21NetworkStorageSession36setDomainsWithCrossPageStorageAccessERKN3WTF7HashMapINS_17RegistrableDomainES3_NS1_11DefaultHashIS3_EENS1_10HashTraitsIS3_EES7_NS1_15HashTableTraitsEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7WebCore21NetworkStorageSession36setDomainsWithCrossPageStorageAccessERKN3WTF7HashMapINS_17RegistrableDomainES3_NS1_11DefaultHashIS3_EENS1_10HashTraitsIS3_EES7_NS1_15HashTableTraitsEEE()');
  },

  onLeave(log, retval, state) {
  }
});
