/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7WebCore11FrameLoader17HistoryController14setCurrentItemERNS_11HistoryItemE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7WebCore11FrameLoader17HistoryController14setCurrentItemERNS_11HistoryItemE()');
  },

  onLeave(log, retval, state) {
  }
});
