/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7WebCore21AudioHardwareListener19setCreationFunctionEON3WTF8FunctionIFNS1_3RefIS0_NS1_12RawPtrTraitsIS0_EEEERNS0_6ClientEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7WebCore21AudioHardwareListener19setCreationFunctionEON3WTF8FunctionIFNS1_3RefIS0_NS1_12RawPtrTraitsIS0_EEEERNS0_6ClientEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
