/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7WebCore21RemoteCommandListener19setCreationFunctionEON3WTF8FunctionIFNSt3__110unique_ptrIS0_NS3_14default_deleteIS0_EEEERNS_27RemoteCommandListenerClientEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7WebCore21RemoteCommandListener19setCreationFunctionEON3WTF8FunctionIFNSt3__110unique_ptrIS0_NS3_14default_deleteIS0_EEEERNS_27RemoteCommandListenerClientEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
