/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7WebCore29VideoFullscreenInterfaceAVKit19setPlayerIdentifierENSt3__18optionalIN3WTF16ObjectIdentifierINS_25MediaPlayerIdentifierTypeEEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7WebCore29VideoFullscreenInterfaceAVKit19setPlayerIdentifierENSt3__18optionalIN3WTF16ObjectIdentifierINS_25MediaPlayerIdentifierTypeEEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
