/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7WebCore4Page21setPaymentCoordinatorEONSt3__110unique_ptrINS_18PaymentCoordinatorENS1_14default_deleteIS3_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7WebCore4Page21setPaymentCoordinatorEONSt3__110unique_ptrINS_18PaymentCoordinatorENS1_14default_deleteIS3_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
