/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7WebCore33AudioMediaStreamTrackRendererUnit29setCreateInternalUnitFunctionEON3WTF8FunctionIFNS1_9UniqueRefINS_41AudioMediaStreamTrackRendererInternalUnitEEEONS2_IFimR15AudioBufferListydRjEEEONS2_IFvvEEEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7WebCore33AudioMediaStreamTrackRendererUnit29setCreateInternalUnitFunctionEON3WTF8FunctionIFNS1_9UniqueRefINS_41AudioMediaStreamTrackRendererInternalUnitEEEONS2_IFimR15AudioBufferListydRjEEEONS2_IFvvEEEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
