/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7WebCore16HTMLInputElement8setFilesEON3WTF6RefPtrINS_8FileListENS1_12RawPtrTraitsIS3_EENS1_21DefaultRefDerefTraitsIS3_EEEENS_18WasSetByJavaScriptE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7WebCore16HTMLInputElement8setFilesEON3WTF6RefPtrINS_8FileListENS1_12RawPtrTraitsIS3_EENS1_21DefaultRefDerefTraitsIS3_EEEENS_18WasSetByJavaScriptE()');
  },

  onLeave(log, retval, state) {
  }
});
