/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7WebCore13GraphicsLayer20setReplicatedByLayerEON3WTF6RefPtrIS0_NS1_12RawPtrTraitsIS0_EENS1_21DefaultRefDerefTraitsIS0_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7WebCore13GraphicsLayer20setReplicatedByLayerEON3WTF6RefPtrIS0_NS1_12RawPtrTraitsIS0_EENS1_21DefaultRefDerefTraitsIS0_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
