/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7WebCore19ResourceRequestBase20setSystemPreviewInfoERKNS_17SystemPreviewInfoE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7WebCore19ResourceRequestBase20setSystemPreviewInfoERKNS_17SystemPreviewInfoE()');
  },

  onLeave(log, retval, state) {
  }
});
