/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7WebCore18SourceBufferParser29setCallOnClientThreadCallbackEON3WTF8FunctionIFvONS2_IFvvEEEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7WebCore18SourceBufferParser29setCallOnClientThreadCallbackEON3WTF8FunctionIFvONS2_IFvvEEEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
