/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7WebCore26AudioSourceProviderAVFObjC29setRingBufferCreationCallbackEON3WTF8FunctionIFNS1_9UniqueRefINS_12CARingBufferEEEvEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7WebCore26AudioSourceProviderAVFObjC29setRingBufferCreationCallbackEON3WTF8FunctionIFNS1_9UniqueRefINS_12CARingBufferEEEvEEE()');
  },

  onLeave(log, retval, state) {
  }
});
