/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK7WebCore9FrameView15topContentInsetENS_10ScrollView19TopContentInsetTypeE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK7WebCore9FrameView15topContentInsetENS_10ScrollView19TopContentInsetTypeE()');
  },

  onLeave(log, retval, state) {
  }
});
