/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK7WebCore21NetworkStorageSession17setCookiesFromDOMERKN3WTF3URLERKNS_12SameSiteInfoES4_NSt3__18optionalINS1_16ObjectIdentifierINS_19FrameIdentifierTypeEEEEENS9_INSA_INS_18PageIdentifierTypeEEEEENS_12ShouldAskITPERKNS1_6StringENS_35ShouldRelaxThirdPartyCookieBlockingE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK7WebCore21NetworkStorageSession17setCookiesFromDOMERKN3WTF3URLERKNS_12SameSiteInfoES4_NSt3__18optionalINS1_16ObjectIdentifierINS_19FrameIdentifierTypeEEEEENS9_INSA_INS_18PageIdentifierTypeEEEEENS_12ShouldAskITPERKNS1_6StringENS_35ShouldRelaxThirdPartyCookieBlockingE()');
  },

  onLeave(log, retval, state) {
  }
});
