/*
 * Auto-generated by Frida. Please modify to match the signature of _ZThn144_N7WebCore16HTMLMediaElement8setMutedEb.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZThn144_N7WebCore16HTMLMediaElement8setMutedEb()');
  },

  onLeave(log, retval, state) {
  }
});
