/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt3__17promiseIvE28set_exception_at_thread_exitESt13exception_ptr.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt3__17promiseIvE28set_exception_at_thread_exitESt13exception_ptr()');
  },

  onLeave(log, retval, state) {
  }
});
