/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNSt3__115basic_streambufIcNS_11char_traitsIcEEE4setpEPcS4_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNSt3__115basic_streambufIcNS_11char_traitsIcEEE4setpEPcS4_()');
  },

  onLeave(log, retval, state) {
  }
});
