/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN11CRCHNetwork23rescoreWithWordLMVectorEPvS0_S0_17CHRecognitionTypeRNSt3__16vectorIjNS2_9allocatorIjEEEERNS2_3mapINS2_12basic_stringIcNS2_11char_traitsIcEENS4_IcEEEEiNS2_4lessISD_EENS4_INS2_4pairIKSD_iEEEEEERKNS3_IyNS4_IyEEEEiNS2_3setIiNSE_IiEENS4_IiEEEEST_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN11CRCHNetwork23rescoreWithWordLMVectorEPvS0_S0_17CHRecognitionTypeRNSt3__16vectorIjNS2_9allocatorIjEEEERNS2_3mapINS2_12basic_stringIcNS2_11char_traitsIcEENS4_IcEEEEiNS2_4lessISD_EENS4_INS2_4pairIKSD_iEEEEEERKNS3_IyNS4_IyEEEEiNS2_3setIiNSE_IiEENS4_IiEEEEST_()');
  },

  onLeave(log, retval, state) {
  }
});
