/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN11CRCHNetwork26addCWComposedCharacterEdgeERKS_R16CRCHNodeTupleMapIyEmmybmRK11NetworkEdgeRNSt3__13setImNS8_4lessImEENS8_9allocatorImEEEERNS8_6vectorIS5_NSC_IS5_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN11CRCHNetwork26addCWComposedCharacterEdgeERKS_R16CRCHNodeTupleMapIyEmmybmRK11NetworkEdgeRNSt3__13setImNS8_4lessImEENS8_9allocatorImEEEERNS8_6vectorIS5_NSC_IS5_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
