/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN11CRCHNetwork8compose8ERKS_PvS2_yyyRNSt3__13mapINS3_12basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEiNS3_4lessISA_EENS8_INS3_4pairIKSA_iEEEEEEmS2_ybR16CRCHNodeTupleMapIyERNS3_6vectorI11NetworkEdgeNS8_ISN_EEEERNS3_3setImNSB_ImEENS8_ImEEEESV_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN11CRCHNetwork8compose8ERKS_PvS2_yyyRNSt3__13mapINS3_12basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEiNS3_4lessISA_EENS8_INS3_4pairIKSA_iEEEEEEmS2_ybR16CRCHNodeTupleMapIyERNS3_6vectorI11NetworkEdgeNS8_ISN_EEEERNS3_3setImNSB_ImEENS8_ImEEEESV_()');
  },

  onLeave(log, retval, state) {
  }
});
