/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN11CRCHNetwork8compose6ERKS_RS_mmR16CRCHNodeTupleMapImERNSt3__16vectorI11NetworkEdgeNS6_9allocatorIS8_EEEERNS6_3setImNS6_4lessImEENS9_ImEEEESI_b.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN11CRCHNetwork8compose6ERKS_RS_mmR16CRCHNodeTupleMapImERNSt3__16vectorI11NetworkEdgeNS6_9allocatorIS8_EEEERNS6_3setImNS6_4lessImEENS9_ImEEEESI_b()');
  },

  onLeave(log, retval, state) {
  }
});
