TARGET := WoduziCheat
INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = WoduziCheat

WoduziCheat_FILES = WoduziCheat.m
WoduziCheat_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk