/*
 * Auto-generated by Frida. Please modify to match the signature of analytics_set_callback_for_queried_event.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('analytics_set_callback_for_queried_event()');
  },

  onLeave(log, retval, state) {
  }
});
