/*
 * Auto-generated by Frida. Please modify to match the signature of asl_store_set_flags.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('asl_store_set_flags()');
  },

  onLeave(log, retval, state) {
  }
});
