/*
 * Auto-generated by Frida. Please modify to match the signature of mmcs_perform_timer_set_next_fire_date.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('mmcs_perform_timer_set_next_fire_date()');
  },

  onLeave(log, retval, state) {
  }
});
