/*
 * Auto-generated by Frida. Please modify to match the signature of ne_session_is_always_on_vpn_enabled.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('ne_session_is_always_on_vpn_enabled()');
  },

  onLeave(log, retval, state) {
  }
});
