/*
 * Auto-generated by Frida. Please modify to match the signature of ne_socket_set_website_attribution.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('ne_socket_set_website_attribution()');
  },

  onLeave(log, retval, state) {
  }
});
