/*
 * Auto-generated by Frida. Please modify to match the signature of set_tquic_expid.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('set_tquic_expid()');
  },

  onLeave(log, retval, state) {
  }
});
