/*
 * Auto-generated by Frida. Please modify to match the signature of __ApplePrivate_gsskrb5_set_default_realm.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('__ApplePrivate_gsskrb5_set_default_realm()');
  },

  onLeave(log, retval, state) {
  }
});
