/*
 * Auto-generated by Frida. Please modify to match the signature of $s7Network19NWProtocolWebSocketC7OptionsC20setAdditionalHeadersyySaySS4name_SS5valuetGFTj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s7Network19NWProtocolWebSocketC7OptionsC20setAdditionalHeadersyySaySS4name_SS5valuetGFTj()');
  },

  onLeave(log, retval, state) {
  }
});
