/*
 * Auto-generated by Frida. Please modify to match the signature of $s8Dispatch0A4DataV6region8locationAC4data_Si6offsettSi_tF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s8Dispatch0A4DataV6region8locationAC4data_Si6offsettSi_tF()');
  },

  onLeave(log, retval, state) {
  }
});
