/*
 * Auto-generated by Frida. Please modify to match the signature of $s8Dispatch25dispatch_source_set_timeryySo03OS_b1_C0C_s6UInt64VA2FtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s8Dispatch25dispatch_source_set_timeryySo03OS_b1_C0C_s6UInt64VA2FtF()');
  },

  onLeave(log, retval, state) {
  }
});
