/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo14OS_dispatch_ioC8DispatchE4read6offset6length5queue0C7Handlerys5Int64V_SiSo0a1_b1_H0CySb_AC0D4DataVSgs5Int32VtctF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo14OS_dispatch_ioC8DispatchE4read6offset6length5queue0C7Handlerys5Int64V_SiSo0a1_b1_H0CySb_AC0D4DataVSgs5Int32VtctF()');
  },

  onLeave(log, retval, state) {
  }
});
