/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo18OS_dispatch_sourceP8DispatchE15setEventHandler7handleryAC0D8WorkItemC_tF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo18OS_dispatch_sourceP8DispatchE15setEventHandler7handleryAC0D8WorkItemC_tF()');
  },

  onLeave(log, retval, state) {
  }
});
