/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN23ktrace_catalog_internal14IterateThreadsEN11flatbuffers14VectorIteratorINS0_6OffsetIN18KernelTraceCatalog6ThreadEEEPKS4_EES8_U13block_pointerFbS7_E.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN23ktrace_catalog_internal14IterateThreadsEN11flatbuffers14VectorIteratorINS0_6OffsetIN18KernelTraceCatalog6ThreadEEEPKS4_EES8_U13block_pointerFbS7_E()');
  },

  onLeave(log, retval, state) {
  }
});
