/*
 * Auto-generated by Frida. Please modify to match the signature of ktrace_set_only_do_time_sensitive_postprocess.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('ktrace_set_only_do_time_sensitive_postprocess()');
  },

  onLeave(log, retval, state) {
  }
});
