/*
 * Auto-generated by Frida. Please modify to match the signature of ktrace_set_dsc_unslid_base_addresses.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('ktrace_set_dsc_unslid_base_addresses()');
  },

  onLeave(log, retval, state) {
  }
});
