/*
 * Auto-generated by Frida. Please modify to match the signature of _Z11setterDummyP11objc_objectP13objc_selectorS0_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_Z11setterDummyP11objc_objectP13objc_selectorS0_()');
  },

  onLeave(log, retval, state) {
  }
});
