/*
 * Auto-generated by Frida. Please modify to match the signature of $s17CoreSuggestionsUI26SGBannerContentHostingViewC29actionButtonLeadingEdgeOffset0A8Graphics7CGFloatVyF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s17CoreSuggestionsUI26SGBannerContentHostingViewC29actionButtonLeadingEdgeOffset0A8Graphics7CGFloatVyF()');
  },

  onLeave(log, retval, state) {
  }
});
