/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN4AMCP13Feature_Flags23set_force_mock_dsp_typeEb.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN4AMCP13Feature_Flags23set_force_mock_dsp_typeEb()');
  },

  onLeave(log, retval, state) {
  }
});
