/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN4AMCP4Node27set_register_client_handlerERKNSt3__18functionIFvjEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN4AMCP4Node27set_register_client_handlerERKNSt3__18functionIFvjEEE()');
  },

  onLeave(log, retval, state) {
  }
});
