/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN4AMCP15Boolean_Control9set_valueEb.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN4AMCP15Boolean_Control9set_valueEb()');
  },

  onLeave(log, retval, state) {
  }
});
