/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN4AMCP9IOContext21set_buffer_frame_sizeEj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN4AMCP9IOContext21set_buffer_frame_sizeEj()');
  },

  onLeave(log, retval, state) {
  }
});
