/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN4AMCP9IOContext21set_client_io_handlerERKNSt3__18functionIFvjRKNS_15Proc_Cycle_InfoEmPNS_11Proc_StreamEmS7_EEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN4AMCP9IOContext21set_client_io_handlerERKNSt3__18functionIFvjRKNS_15Proc_Cycle_InfoEmPNS_11Proc_StreamEmS7_EEE()');
  },

  onLeave(log, retval, state) {
  }
});
