/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN4AMCP16Selector_Control15set_multi_valueERKNSt3__16vectorIjNS1_9allocatorIjEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN4AMCP16Selector_Control15set_multi_valueERKNSt3__16vectorIjNS1_9allocatorIjEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
