/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN4AMCP9IOContext23set_os_workgroup_handleERKN5caulk4mach29os_workgroup_interval_managedE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN4AMCP9IOContext23set_os_workgroup_handleERKN5caulk4mach29os_workgroup_interval_managedE()');
  },

  onLeave(log, retval, state) {
  }
});
