/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN4AMCP8DSP_Node21set_end_cycle_handlerERKNSt3__18functionIFvjRKNS_15Proc_Cycle_InfoEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN4AMCP8DSP_Node21set_end_cycle_handlerERKNSt3__18functionIFvjRKNS_15Proc_Cycle_InfoEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
