/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN4AMCP13Level_Control25set_scalar_value_and_waitEf.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN4AMCP13Level_Control25set_scalar_value_and_waitEf()');
  },

  onLeave(log, retval, state) {
  }
});
