/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN4AMCP14Slider_Control18set_value_and_waitEj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN4AMCP14Slider_Control18set_value_and_waitEj()');
  },

  onLeave(log, retval, state) {
  }
});
