/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK4AMCP6Object42set_property_value_with_qualifier_and_waitERKNS_7AddressERKNS_5ThingES6_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK4AMCP6Object42set_property_value_with_qualifier_and_waitERKNS_7AddressERKNS_5ThingES6_()');
  },

  onLeave(log, retval, state) {
  }
});
