/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK4AMCP6Object27set_property_value_and_waitERKNS_7AddressERKNS_5ThingE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK4AMCP6Object27set_property_value_and_waitERKNS_7AddressERKNS_5ThingE()');
  },

  onLeave(log, retval, state) {
  }
});
