/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK4AMCP5Clock24set_sample_rate_and_waitEd.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK4AMCP5Clock24set_sample_rate_and_waitEd()');
  },

  onLeave(log, retval, state) {
  }
});
