/*
 * Auto-generated by Frida. Please modify to match the signature of nghttp2_session_callbacks_set_on_invalid_header_callback2.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('nghttp2_session_callbacks_set_on_invalid_header_callback2()');
  },

  onLeave(log, retval, state) {
  }
});
