/*
 * Auto-generated by Frida. Please modify to match the signature of $s5JetUI10DimensionsV30cumulativeLanguageAwareOutsets2of14compatibleWithSo12UIEdgeInsetsVSayAA12AnyDimension_pG_So17UITraitCollectionCtFZ.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s5JetUI10DimensionsV30cumulativeLanguageAwareOutsets2of14compatibleWithSo12UIEdgeInsetsVSayAA12AnyDimension_pG_So17UITraitCollectionCtFZ()');
  },

  onLeave(log, retval, state) {
  }
});
