/*
 * Auto-generated by Frida. Please modify to match the signature of $s5JetUI7MarginsV6insets5childACSo12UIEdgeInsetsV_AA6Layout_AA10MeasurableptcfC.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s5JetUI7MarginsV6insets5childACSo12UIEdgeInsetsV_AA6Layout_AA10MeasurableptcfC()');
  },

  onLeave(log, retval, state) {
  }
});
