/*
 * Auto-generated by Frida. Please modify to match the signature of $s5JetUI0A18UIBugCompatibilityV6enable_7performxAC_xyKXEtKlFZ.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s5JetUI0A18UIBugCompatibilityV6enable_7performxAC_xyKXEtKlFZ()');
  },

  onLeave(log, retval, state) {
  }
});
