/*
 * Auto-generated by Frida. Please modify to match the signature of $s5JetUI19LineHeightDimensionV20languageAwareOutsets14compatibleWithSo12UIEdgeInsetsVSo17UITraitCollectionC_tF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s5JetUI19LineHeightDimensionV20languageAwareOutsets14compatibleWithSo12UIEdgeInsetsVSo17UITraitCollectionC_tF()');
  },

  onLeave(log, retval, state) {
  }
});
