/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo6CGRectV5JetUIE9insetting11bySeparator2inAbC0F0V_So18UITraitEnvironment_ptF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo6CGRectV5JetUIE9insetting11bySeparator2inAbC0F0V_So18UITraitEnvironment_ptF()');
  },

  onLeave(log, retval, state) {
  }
});
