/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo6CGSizeV5JetUIE6adding7outsetsABSo12UIEdgeInsetsV_tF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo6CGSizeV5JetUIE6adding7outsetsABSo12UIEdgeInsetsV_tF()');
  },

  onLeave(log, retval, state) {
  }
});
