/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo18NSAttributedStringC5JetUIE20languageAwareOutsets12whenUsedWithSo12UIEdgeInsetsVSo6UIFontC_tF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo18NSAttributedStringC5JetUIE20languageAwareOutsets12whenUsedWithSo12UIEdgeInsetsVSo6UIFontC_tF()');
  },

  onLeave(log, retval, state) {
  }
});
