/*
 * Auto-generated by Frida. Please modify to match the signature of $s7Combine9PublisherPAAs5NeverO7FailureRtzrlE03setD4Type2toAA10PublishersO03SetdF0Vy_xqd__Gqd__m_ts5ErrorRd__lF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s7Combine9PublisherPAAs5NeverO7FailureRtzrlE03setD4Type2toAA10PublishersO03SetdF0Vy_xqd__Gqd__m_ts5ErrorRd__lF()');
  },

  onLeave(log, retval, state) {
  }
});
