/*
 * Auto-generated by Frida. Please modify to match the signature of $s14AttributeGraph0A0V8applying6offsetACyqd__GAA13PointerOffsetVyxqd__G_tlF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s14AttributeGraph0A0V8applying6offsetACyqd__GAA13PointerOffsetVyxqd__G_tlF()');
  },

  onLeave(log, retval, state) {
  }
});
