/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo11AGTupleTypea14AttributeGraphE6offset2at2asS2i_xmtlF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo11AGTupleTypea14AttributeGraphE6offset2at2asS2i_xmtlF()');
  },

  onLeave(log, retval, state) {
  }
});
