/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN8DSPGraph3Box8isogroupERNSt3__113unordered_setIPS0_NS1_4hashIS3_EENS1_8equal_toIS3_EENS1_9allocatorIS3_EEEEPNS_8IsoGroupE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN8DSPGraph3Box8isogroupERNSt3__113unordered_setIPS0_NS1_4hashIS3_EENS1_8equal_toIS3_EENS1_9allocatorIS3_EEEEPNS_8IsoGroupE()');
  },

  onLeave(log, retval, state) {
  }
});
