/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN8DSPGraph5FCBox8isogroupERNSt3__113unordered_setIPNS_3BoxENS1_4hashIS4_EENS1_8equal_toIS4_EENS1_9allocatorIS4_EEEEPNS_8IsoGroupE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN8DSPGraph5FCBox8isogroupERNSt3__113unordered_setIPNS_3BoxENS1_4hashIS4_EENS1_8equal_toIS4_EENS1_9allocatorIS4_EEEEPNS_8IsoGroupE()');
  },

  onLeave(log, retval, state) {
  }
});
