/*
 * Auto-generated by Frida. Please modify to match the signature of $ss15FlattenSequenceVsSlRzSl7ElementRpzrlE5index_8offsetByABsSlRzSlADRQrlE5IndexVyx_GAI_SitF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$ss15FlattenSequenceVsSlRzSl7ElementRpzrlE5index_8offsetByABsSlRzSlADRQrlE5IndexVyx_GAI_SitF()');
  },

  onLeave(log, retval, state) {
  }
});
