/*
 * Auto-generated by Frida. Please modify to match the signature of $ss14_CollectionBoxC6_index_8offsetBy07limitedE0s09_AnyIndexB0_pSgsAF_p_SisAF_ptF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$ss14_CollectionBoxC6_index_8offsetBy07limitedE0s09_AnyIndexB0_pSgsAF_p_SisAF_ptF()');
  },

  onLeave(log, retval, state) {
  }
});
