/*
 * Auto-generated by Frida. Please modify to match the signature of $ss18LazyFilterSequenceVsSlRzrlE5index_8offsetBy07limitedF05IndexQzSgAG_SiAGtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$ss18LazyFilterSequenceVsSlRzrlE5index_8offsetBy07limitedF05IndexQzSgAG_SiAGtF()');
  },

  onLeave(log, retval, state) {
  }
});
