/*
 * Auto-generated by Frida. Please modify to match the signature of $ss13_UnsafeBitsetV4join4word3bitS2i_SitFZ.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$ss13_UnsafeBitsetV4join4word3bitS2i_SitFZ()');
  },

  onLeave(log, retval, state) {
  }
});
