/*
 * Auto-generated by Frida. Please modify to match the signature of $ss10SetAlgebraP10isSuperset2ofSbx_tFTj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$ss10SetAlgebraP10isSuperset2ofSbx_tFTj()');
  },

  onLeave(log, retval, state) {
  }
});
