/*
 * Auto-generated by Frida. Please modify to match the signature of $ss17_AnyCollectionBoxC10_formIndex_8offsetByys01_aeC0_pz_SitF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$ss17_AnyCollectionBoxC10_formIndex_8offsetByys01_aeC0_pz_SitF()');
  },

  onLeave(log, retval, state) {
  }
});
