/*
 * Auto-generated by Frida. Please modify to match the signature of $ss13_UnsafeBitsetV8IteratorV5indexSivM.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$ss13_UnsafeBitsetV8IteratorV5indexSivM()');
  },

  onLeave(log, retval, state) {
  }
});
