/*
 * Auto-generated by Frida. Please modify to match the signature of $ss11_UIntBufferV5IndexV9bitOffsets5UInt8VvM.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$ss11_UIntBufferV5IndexV9bitOffsets5UInt8VvM()');
  },

  onLeave(log, retval, state) {
  }
});
