/*
 * Auto-generated by Frida. Please modify to match the signature of $ss26AnyBidirectionalCollectionV9formIndex_8offsetBy07limitedG0Sbs0aE0Vz_SiAGtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$ss26AnyBidirectionalCollectionV9formIndex_8offsetBy07limitedG0Sbs0aE0Vz_SiAGtF()');
  },

  onLeave(log, retval, state) {
  }
});
