/*
 * Auto-generated by Frida. Please modify to match the signature of $ss26AnyBidirectionalCollectionV9formIndex_8offsetByys0aE0Vz_SitF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$ss26AnyBidirectionalCollectionV9formIndex_8offsetByys0aE0Vz_SitF()');
  },

  onLeave(log, retval, state) {
  }
});
