/*
 * Auto-generated by Frida. Please modify to match the signature of $ss27_BidirectionalCollectionBoxC6_index_8offsetBy07limitedF0s09_AnyIndexC0_pSgsAF_p_SisAF_ptF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$ss27_BidirectionalCollectionBoxC6_index_8offsetBy07limitedF0s09_AnyIndexC0_pSgsAF_p_SisAF_ptF()');
  },

  onLeave(log, retval, state) {
  }
});
