/*
 * Auto-generated by Frida. Please modify to match the signature of $sSD8_VariantV8setValue_6forKeyyq_n_xtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSD8_VariantV8setValue_6forKeyyq_n_xtF()');
  },

  onLeave(log, retval, state) {
  }
});
