/*
 * Auto-generated by Frida. Please modify to match the signature of $sSh10isSuperset2ofSbqd__n_t7ElementQyd__RszSTRd__lF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSh10isSuperset2ofSbqd__n_t7ElementQyd__RszSTRd__lF()');
  },

  onLeave(log, retval, state) {
  }
});
