/*
 * Auto-generated by Frida. Please modify to match the signature of $sSK5index_8offsetBy07limitedC05IndexQzSgAE_SiAEtFTj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSK5index_8offsetBy07limitedC05IndexQzSgAE_SiAEtFTj()');
  },

  onLeave(log, retval, state) {
  }
});
