/*
 * Auto-generated by Frida. Please modify to match the signature of $sSlsE5index_8offsetBy5IndexQzAD_qd__tSzRd__lF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSlsE5index_8offsetBy5IndexQzAD_qd__tSzRd__lF()');
  },

  onLeave(log, retval, state) {
  }
});
