/*
 * Auto-generated by Frida. Please modify to match the signature of $sSR5index_8offsetBy07limitedC0SiSgSi_S2itF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSR5index_8offsetBy07limitedC0SiSgSi_S2itF()');
  },

  onLeave(log, retval, state) {
  }
});
