/*
 * Auto-generated by Frida. Please modify to match the signature of $sSS9UTF16ViewV5index_8offsetBy07limitedE0SS5IndexVSgAG_SiAGtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSS9UTF16ViewV5index_8offsetBy07limitedE0SS5IndexVSgAG_SiAGtF()');
  },

  onLeave(log, retval, state) {
  }
});
