/*
 * Auto-generated by Frida. Please modify to match the signature of $sSv4load14fromByteOffset2asxSi_xmtlF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSv4load14fromByteOffset2asxSi_xmtlF()');
  },

  onLeave(log, retval, state) {
  }
});
