/*
 * Auto-generated by Frida. Please modify to match the signature of $sSw10storeBytes2of12toByteOffset2asyx_SixmtlF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSw10storeBytes2of12toByteOffset2asyx_SixmtlF()');
  },

  onLeave(log, retval, state) {
  }
});
