/*
 * Auto-generated by Frida. Please modify to match the signature of $s12NIOIMAPCore217OrderedDictionaryV6offsetx3key_q_5valuetSi_tcig.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s12NIOIMAPCore217OrderedDictionaryV6offsetx3key_q_5valuetSi_tcig()');
  },

  onLeave(log, retval, state) {
  }
});
