/*
 * Auto-generated by Frida. Please modify to match the signature of $s12NIOIMAPCore210ByteBufferV012setRepeatingB0_5count2atSis5UInt8V_S2itF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s12NIOIMAPCore210ByteBufferV012setRepeatingB0_5count2atSis5UInt8V_S2itF()');
  },

  onLeave(log, retval, state) {
  }
});
