/*
 * Auto-generated by Frida. Please modify to match the signature of $s12NIOIMAPCore25DequeV13_UnsafeHandleV23uncheckedReplaceInPlace9inOffsets4withySnySiG_qd__t7ElementQyd__RszSlRd__lF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s12NIOIMAPCore25DequeV13_UnsafeHandleV23uncheckedReplaceInPlace9inOffsets4withySnySiG_qd__t7ElementQyd__RszSlRd__lF()');
  },

  onLeave(log, retval, state) {
  }
});
