/*
 * Auto-generated by Frida. Please modify to match the signature of $s12NIOIMAPCore213_UnsafeBitsetV12makeIteratorAC0E0VyF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s12NIOIMAPCore213_UnsafeBitsetV12makeIteratorAC0E0VyF()');
  },

  onLeave(log, retval, state) {
  }
});
