/*
 * Auto-generated by Frida. Please modify to match the signature of $s12NIOIMAPCore210_HashTableV12UnsafeHandleV14adjustContents38preparingForInsertionOfElementAtOffset2inySi_xtSkRzSH0L0RpzlF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s12NIOIMAPCore210_HashTableV12UnsafeHandleV14adjustContents38preparingForInsertionOfElementAtOffset2inySi_xtSkRzSH0L0RpzlF()');
  },

  onLeave(log, retval, state) {
  }
});
