/*
 * Auto-generated by Frida. Please modify to match the signature of $s12NIOIMAPCore25DequeV13_UnsafeHandleV8segments10forOffsetsAA01_C13WrappedBufferVyxGSnySiG_tF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s12NIOIMAPCore25DequeV13_UnsafeHandleV8segments10forOffsetsAA01_C13WrappedBufferVyxGSnySiG_tF()');
  },

  onLeave(log, retval, state) {
  }
});
