/*
 * Auto-generated by Frida. Please modify to match the signature of $s12NIOIMAPCore210ByteBufferV023_setBytesAssumingUniqueC6Access_2atySW_s6UInt32VtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s12NIOIMAPCore210ByteBufferV023_setBytesAssumingUniqueC6Access_2atySW_s6UInt32VtF()');
  },

  onLeave(log, retval, state) {
  }
});
