/*
 * Auto-generated by Frida. Please modify to match the signature of $s12NIOIMAPCore210ByteBufferV12_setSlowPath5bytes2ats6UInt32Vx_AHtSTRzs5UInt8V7ElementRtzlF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s12NIOIMAPCore210ByteBufferV12_setSlowPath5bytes2ats6UInt32Vx_AHtSTRzs5UInt8V7ElementRtzlF()');
  },

  onLeave(log, retval, state) {
  }
});
