/*
 * Auto-generated by Frida. Please modify to match the signature of $sSq12NIOIMAPCore2AA10ByteBufferVRszlE010setOrWriteC0ySiACzF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSq12NIOIMAPCore2AA10ByteBufferVRszlE010setOrWriteC0ySiACzF()');
  },

  onLeave(log, retval, state) {
  }
});
