/*
 * Auto-generated by Frida. Please modify to match the signature of _vproc_transaction_set_clean_callback.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_vproc_transaction_set_clean_callback()');
  },

  onLeave(log, retval, state) {
  }
});
