/*
 * Auto-generated by Frida. Please modify to match the signature of xpc_connection_enable_termination_imminent_event.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('xpc_connection_enable_termination_imminent_event()');
  },

  onLeave(log, retval, state) {
  }
});
