/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN5caulk4mach11this_thread12set_priorityERKNSt3__17variantIJNS0_6thread12priority_qosENS4_17priority_realtimeENS4_17priority_absoluteEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN5caulk4mach11this_thread12set_priorityERKNSt3__17variantIJNS0_6thread12priority_qosENS4_17priority_realtimeENS4_17priority_absoluteEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
