/*
 * Auto-generated by Frida. Please modify to match the signature of $s14CloudSharingUI0B16OptionsViewModelC018collaborationShareD013layoutMargins19userDidChangeOption011contentSizelM0ACSo016_SWCollaborationhD0CSg_05SwiftC010EdgeInsetsVySS_SSSbAJtcSgySo6CGSizeVcSgtcfC.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s14CloudSharingUI0B16OptionsViewModelC018collaborationShareD013layoutMargins19userDidChangeOption011contentSizelM0ACSo016_SWCollaborationhD0CSg_05SwiftC010EdgeInsetsVySS_SSSbAJtcSgySo6CGSizeVcSgtcfC()');
  },

  onLeave(log, retval, state) {
  }
});
