/*
 * Auto-generated by Frida. Please modify to match the signature of $s11ActivityKit0A21AuthorizationManagingP24setFrequentPushesEnabled3for4withySS_AA0aC7OptionsVtKFTj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s11ActivityKit0A21AuthorizationManagingP24setFrequentPushesEnabled3for4withySS_AA0aC7OptionsVtKFTj()');
  },

  onLeave(log, retval, state) {
  }
});
