/*
 * Auto-generated by Frida. Please modify to match the signature of $s11ActivityKit0A13AuthorizationC17setFrequentPushes7enabled3forySb_SStKFTj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s11ActivityKit0A13AuthorizationC17setFrequentPushes7enabled3forySb_SStKFTj()');
  },

  onLeave(log, retval, state) {
  }
});
