/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7morphun6dialog15SemanticFeature12boundedValueERKNSt3__112basic_stringIDsNS2_11char_traitsIDsEENS2_9allocatorIDsEEEERKNS2_3setIS8_NS2_4lessIS8_EENS6_IS8_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7morphun6dialog15SemanticFeature12boundedValueERKNSt3__112basic_stringIDsNS2_11char_traitsIDsEENS2_9allocatorIDsEEEERKNS2_3setIS8_NS2_4lessIS8_EENS6_IS8_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
