/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7morphun4lang8features39LanguageGrammarFeatures_GrammarCategoryC2ERKNSt3__112basic_stringIDsNS3_11char_traitsIDsEENS3_9allocatorIDsEEEERKNS3_3setIS9_NS3_4lessIS9_EENS7_IS9_EEEERKNS3_8multimapIS9_S9_SE_NS7_INS3_4pairISA_S9_EEEEEERKNS3_3mapINS3_17basic_string_viewIDsS6_EESN_NSD_ISS_EENS7_INSK_IKSS_SN_EEEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7morphun4lang8features39LanguageGrammarFeatures_GrammarCategoryC2ERKNSt3__112basic_stringIDsNS3_11char_traitsIDsEENS3_9allocatorIDsEEEERKNS3_3setIS9_NS3_4lessIS9_EENS7_IS9_EEEERKNS3_8multimapIS9_S9_SE_NS7_INS3_4pairISA_S9_EEEEEERKNS3_3mapINS3_17basic_string_viewIDsS6_EESN_NSD_ISS_EENS7_INSK_IKSS_SN_EEEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
