/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7morphun6dialog5proxy21RequestContextBuilder15setOutputLocaleERKNS_4util7ULocaleE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7morphun6dialog5proxy21RequestContextBuilder15setOutputLocaleERKNS_4util7ULocaleE()');
  },

  onLeave(log, retval, state) {
  }
});
