/*
 * Auto-generated by Frida. Please modify to match the signature of $s7SwiftUI15InsettableShapePAAE12strokeBorder_5style11antialiasedQrqd___AA11StrokeStyleVSbtAA0dJ0Rd__lF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s7SwiftUI15InsettableShapePAAE12strokeBorder_5style11antialiasedQrqd___AA11StrokeStyleVSbtAA0dJ0Rd__lF()');
  },

  onLeave(log, retval, state) {
  }
});
