/*
 * Auto-generated by Frida. Please modify to match the signature of $s7SwiftUI34_InsettableBackgroundShapeModifierVyxq_GAA04ViewF0A2aEP05_makeG4List8modifier6inputs4bodyAA01_gI7OutputsVAA11_GraphValueVyxG_AA01_gI6InputsVAlA01_N0V_AQtctFZTW.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s7SwiftUI34_InsettableBackgroundShapeModifierVyxq_GAA04ViewF0A2aEP05_makeG4List8modifier6inputs4bodyAA01_gI7OutputsVAA11_GraphValueVyxG_AA01_gI6InputsVAlA01_N0V_AQtctFZTW()');
  },

  onLeave(log, retval, state) {
  }
});
