/*
 * Auto-generated by Frida. Please modify to match the signature of $s7SwiftUI15InsettableShapePAAE12strokeBorder9lineWidth11antialiasedQr12CoreGraphics7CGFloatV_SbtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s7SwiftUI15InsettableShapePAAE12strokeBorder9lineWidth11antialiasedQr12CoreGraphics7CGFloatV_SbtF()');
  },

  onLeave(log, retval, state) {
  }
});
