/*
 * Auto-generated by Frida. Please modify to match the signature of $s7SwiftUI15DynamicPropertyP05_makeD02in9container11fieldOffset6inputsyAA01_cD6BufferVz_AA11_GraphValueVyqd__GSiAA01_L6InputsVztlFZTj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s7SwiftUI15DynamicPropertyP05_makeD02in9container11fieldOffset6inputsyAA01_cD6BufferVz_AA11_GraphValueVyqd__GSiAA01_L6InputsVztlFZTj()');
  },

  onLeave(log, retval, state) {
  }
});
