/*
 * Auto-generated by Frida. Please modify to match the signature of $s7SwiftUI17_ScrollViewConfigV13contentInsetsAA04EdgeG0VvM.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s7SwiftUI17_ScrollViewConfigV13contentInsetsAA04EdgeG0VvM()');
  },

  onLeave(log, retval, state) {
  }
});
