/*
 * Auto-generated by Frida. Please modify to match the signature of $s7SwiftUI29UIViewControllerRepresentablePAAE06_resetcD0_11coordinator7destroyy0cD4TypeQz_11CoordinatorQzyyXEtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s7SwiftUI29UIViewControllerRepresentablePAAE06_resetcD0_11coordinator7destroyy0cD4TypeQz_11CoordinatorQzyyXEtF()');
  },

  onLeave(log, retval, state) {
  }
});
