/*
 * Auto-generated by Frida. Please modify to match the signature of $s7SwiftUI14InsetListStyleV9_makeView5value6inputsAA01_G7OutputsVAA11_GraphValueVyAA01_dL0VyACxGG_AA01_G6InputsVtSHRzlFZ.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s7SwiftUI14InsetListStyleV9_makeView5value6inputsAA01_G7OutputsVAA11_GraphValueVyAA01_dL0VyACxGG_AA01_G6InputsVtSHRzlFZ()');
  },

  onLeave(log, retval, state) {
  }
});
