/*
 * Auto-generated by Frida. Please modify to match the signature of $s7SwiftUI11OffsetShapeV14animatableDataAA14AnimatablePairVy0gF0QzAFy12CoreGraphics7CGFloatVAKGGvs.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s7SwiftUI11OffsetShapeV14animatableDataAA14AnimatablePairVy0gF0QzAFy12CoreGraphics7CGFloatVAKGGvs()');
  },

  onLeave(log, retval, state) {
  }
});
