/*
 * Auto-generated by Frida. Please modify to match the signature of $s7SwiftUI18_InsetViewModifierV7content4edge7regions7spacing12alignmentKeyACyxGx_AA4EdgeOAA15SafeAreaRegionsV12CoreGraphics7CGFloatVSgAA09AlignmentK0VtcfC.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s7SwiftUI18_InsetViewModifierV7content4edge7regions7spacing12alignmentKeyACyxGx_AA4EdgeOAA15SafeAreaRegionsV12CoreGraphics7CGFloatVSgAA09AlignmentK0VtcfC()');
  },

  onLeave(log, retval, state) {
  }
});
