/*
 * Auto-generated by Frida. Please modify to match the signature of $s7SwiftUI9RectangleV6_InsetV6amountAE12CoreGraphics7CGFloatV_tcfC.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s7SwiftUI9RectangleV6_InsetV6amountAE12CoreGraphics7CGFloatV_tcfC()');
  },

  onLeave(log, retval, state) {
  }
});
