/*
 * Auto-generated by Frida. Please modify to match the signature of $s7SwiftUI17_ScrollableLayoutP18decelerationTarget13contentOffset015originalContentH08velocity4sizeSo7CGPointVSgAJ_AjA9_VelocityVySo6CGSizeVAOSQ12CoreGraphicsyHCg_GAOtFTj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s7SwiftUI17_ScrollableLayoutP18decelerationTarget13contentOffset015originalContentH08velocity4sizeSo7CGPointVSgAJ_AjA9_VelocityVySo6CGSizeVAOSQ12CoreGraphicsyHCg_GAOtFTj()');
  },

  onLeave(log, retval, state) {
  }
});
