/*
 * Auto-generated by Frida. Please modify to match the signature of $s7SwiftUI34_InsettableBackgroundShapeModifierV9_makeView8modifier6inputs4bodyAA01_H7OutputsVAA11_GraphValueVyACyxq_GG_AA01_H6InputsVAiA01_M0V_AOtctFZ.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s7SwiftUI34_InsettableBackgroundShapeModifierV9_makeView8modifier6inputs4bodyAA01_H7OutputsVAA11_GraphValueVyACyxq_GG_AA01_H6InputsVAiA01_M0V_AOtctFZ()');
  },

  onLeave(log, retval, state) {
  }
});
