/*
 * Auto-generated by Frida. Please modify to match the signature of $s6TipsUI0A12ContentModelC18assetConfiguration3for6assets18updatedColorSchemeSo09TPSAssetsF0CSgSo11TPSDocumentC_So0L0C05SwiftB00jK0OSgtFTj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s6TipsUI0A12ContentModelC18assetConfiguration3for6assets18updatedColorSchemeSo09TPSAssetsF0CSgSo11TPSDocumentC_So0L0C05SwiftB00jK0OSgtFTj()');
  },

  onLeave(log, retval, state) {
  }
});
