/*
 * Auto-generated by Frida. Please modify to match the signature of $s6TipsUI15RemoteVideoViewV9viewModel018showReplayButtonAtD3EndAcA013DocumentAsseteG0C_05SwiftB07BindingVySbGtcfC.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s6TipsUI15RemoteVideoViewV9viewModel018showReplayButtonAtD3EndAcA013DocumentAsseteG0C_05SwiftB07BindingVySbGtcfC()');
  },

  onLeave(log, retval, state) {
  }
});
