/*
 * Auto-generated by Frida. Please modify to match the signature of $s6TipsUI22DocumentAssetViewModelC8document10assetsInfoACSo11TPSDocumentC_0A4Core09TPSAssetsI0Ctcfc.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s6TipsUI22DocumentAssetViewModelC8document10assetsInfoACSo11TPSDocumentC_0A4Core09TPSAssetsI0Ctcfc()');
  },

  onLeave(log, retval, state) {
  }
});
