/*
 * Auto-generated by Frida. Please modify to match the signature of $s6TipsUI18TPSUIAppControllerC18assetConfiguration6assets8language9sizeClass5style0E15FileInfoManagerSo09TPSAssetsF0CSgSo0O0CSg_SSSgSo019UIUserInterfaceSizeJ0VSo0pQ5StyleVSo08TPSAssetlmN0CtFTj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s6TipsUI18TPSUIAppControllerC18assetConfiguration6assets8language9sizeClass5style0E15FileInfoManagerSo09TPSAssetsF0CSgSo0O0CSg_SSSgSo019UIUserInterfaceSizeJ0VSo0pQ5StyleVSo08TPSAssetlmN0CtFTj()');
  },

  onLeave(log, retval, state) {
  }
});
