/*
 * Auto-generated by Frida. Please modify to match the signature of $s6TipsUI19AssetContentModeKeyV12defaultValue05SwiftB00dE0OvgZ.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s6TipsUI19AssetContentModeKeyV12defaultValue05SwiftB00dE0OvgZ()');
  },

  onLeave(log, retval, state) {
  }
});
