/*
 * Auto-generated by Frida. Please modify to match the signature of $s10IronSource33LPMCappingConfigValidatorProtocolP08validateD07enabled5limit4units6ResultOySiAF_AA0C8TimeUnitOAGtSo7NSErrorCGSbSg_SiSgAKSgtFTj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s10IronSource33LPMCappingConfigValidatorProtocolP08validateD07enabled5limit4units6ResultOySiAF_AA0C8TimeUnitOAGtSo7NSErrorCGSbSg_SiSgAKSgtFTj()');
  },

  onLeave(log, retval, state) {
  }
});
