/*
 * Auto-generated by Frida. Please modify to match the signature of $s12VungleAdsSDK0aB0C18setIntegrationName_7versionySS_SStFZ.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s12VungleAdsSDK0aB0C18setIntegrationName_7versionySS_SStFZ()');
  },

  onLeave(log, retval, state) {
  }
});
