/*
 * Auto-generated by Frida. Please modify to match the signature of $s16FBANEndCardSwift09FBANAdEndB14ViewControllerC12dataProvider06configI010assetCache37isFullscreenGestureRecognizersEnabledAcA0deb4DataI0_p_016FBANUIComponentsC0012FBANUIConfigI0_pSo18FBAdVideoCacheable_pSbtcfC.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s16FBANEndCardSwift09FBANAdEndB14ViewControllerC12dataProvider06configI010assetCache37isFullscreenGestureRecognizersEnabledAcA0deb4DataI0_p_016FBANUIComponentsC0012FBANUIConfigI0_pSo18FBAdVideoCacheable_pSbtcfC()');
  },

  onLeave(log, retval, state) {
  }
});
