/*
 * Auto-generated by Frida. Please modify to match the signature of $s18UnitySwiftProtobuf17ExtensibleMessagePAAE17setExtensionValue3ext5valueyAA0eG0CyAA012RepeatedEnumG5FieldVyqd__GxG_Sayqd__GtAA0L0Rd__Si03RawH0Rtd__lF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s18UnitySwiftProtobuf17ExtensibleMessagePAAE17setExtensionValue3ext5valueyAA0eG0CyAA012RepeatedEnumG5FieldVyqd__GxG_Sayqd__GtAA0L0Rd__Si03RawH0Rtd__lF()');
  },

  onLeave(log, retval, state) {
  }
});
