/*
 * Auto-generated by Frida. Please modify to match the signature of $s29FBAudienceNetworkUtilitySwift19FBAdRemoteImageViewC3url10assetCacheAC10Foundation3URLV_So0E14VideoCacheable_ptcfC.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s29FBAudienceNetworkUtilitySwift19FBAdRemoteImageViewC3url10assetCacheAC10Foundation3URLV_So0E14VideoCacheable_ptcfC()');
  },

  onLeave(log, retval, state) {
  }
});
