/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN15BULoggerManager16appender_setmodeE14BUAppenderMode.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN15BULoggerManager16appender_setmodeE14BUAppenderMode()');
  },

  onLeave(log, retval, state) {
  }
});
