/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7plcrash5Unity5async16gnu_ehptr_readerIjE13set_func_baseEj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7plcrash5Unity5async16gnu_ehptr_readerIjE13set_func_baseEj()');
  },

  onLeave(log, retval, state) {
  }
});
