/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN8csj_ugen6ugyoga4Node11setPositionENS0_9DirectionEff.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN8csj_ugen6ugyoga4Node11setPositionENS0_9DirectionEff()');
  },

  onLeave(log, retval, state) {
  }
});
