/*
 * Auto-generated by Frida. Please modify to match the signature of bu_crypt_hmac_reset.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('bu_crypt_hmac_reset()');
  },

  onLeave(log, retval, state) {
  }
});
