/*
 * Auto-generated by Frida. Please modify to match the signature of GAD_GADNativeAdAssetIdentifiers_arm64_12_7_0.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('GAD_GADNativeAdAssetIdentifiers_arm64_12_7_0()');
  },

  onLeave(log, retval, state) {
  }
});
