/*
 * Auto-generated by Frida. Please modify to match the signature of hmdPAG_setup_shared_image_listPAG.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('hmdPAG_setup_shared_image_listPAG()');
  },

  onLeave(log, retval, state) {
  }
});
