/*
 * Auto-generated by Frida. Please modify to match the signature of opt_meth_setoption.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('opt_meth_setoption()');
  },

  onLeave(log, retval, state) {
  }
});
