/*
 * Auto-generated by Frida. Please modify to match the signature of Unityplcrash_async_thread_state_set_reg.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('Unityplcrash_async_thread_state_set_reg()');
  },

  onLeave(log, retval, state) {
  }
});
