/*
 * Auto-generated by Frida. Please modify to match the signature of nw_browse_descriptor_set_include_txt_record.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('nw_browse_descriptor_set_include_txt_record()');
  },

  onLeave(log, retval, state) {
  }
});
