/*
 * Auto-generated by Frida. Please modify to match the signature of nw_connection_group_set_queue.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('nw_connection_group_set_queue()');
  },

  onLeave(log, retval, state) {
  }
});
