/*
 * Auto-generated by Frida. Please modify to match the signature of nw_http_fields_set_field.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('nw_http_fields_set_field()');
  },

  onLeave(log, retval, state) {
  }
});
