/*
 * Auto-generated by Frida. Please modify to match the signature of nw_proxy_config_set_fallback_proxy_agent.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('nw_proxy_config_set_fallback_proxy_agent()');
  },

  onLeave(log, retval, state) {
  }
});
