/*
 * Auto-generated by Frida. Please modify to match the signature of nw_protocol_callbacks_set_input_finished.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('nw_protocol_callbacks_set_input_finished()');
  },

  onLeave(log, retval, state) {
  }
});
