/*
 * Auto-generated by Frida. Please modify to match the signature of nw_parameters_set_initial_data_payload.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('nw_parameters_set_initial_data_payload()');
  },

  onLeave(log, retval, state) {
  }
});
