/*
 * Auto-generated by Frida. Please modify to match the signature of nw_path_flow_registration_set_tfo_cache.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('nw_path_flow_registration_set_tfo_cache()');
  },

  onLeave(log, retval, state) {
  }
});
