/*
 * Auto-generated by Frida. Please modify to match the signature of nw_quic_stream_set_has_datagram_variant_flow_id.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('nw_quic_stream_set_has_datagram_variant_flow_id()');
  },

  onLeave(log, retval, state) {
  }
});
