/*
 * Auto-generated by Frida. Please modify to match the signature of nw_quic_connection_set_server_raw_public_keys.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('nw_quic_connection_set_server_raw_public_keys()');
  },

  onLeave(log, retval, state) {
  }
});
