/*
 * Auto-generated by Frida. Please modify to match the signature of nw_settings_register_quic_log_debug_updates.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('nw_settings_register_quic_log_debug_updates()');
  },

  onLeave(log, retval, state) {
  }
});
