/*
 * Auto-generated by Frida. Please modify to match the signature of nw_tls_set_session_ticket_enabled.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('nw_tls_set_session_ticket_enabled()');
  },

  onLeave(log, retval, state) {
  }
});
