/*
 * Auto-generated by Frida. Please modify to match the signature of nw_ws_options_set_maximum_message_size.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('nw_ws_options_set_maximum_message_size()');
  },

  onLeave(log, retval, state) {
  }
});
