/*
 * Auto-generated by Frida. Please modify to match the signature of _dispatch_source_set_runloop_timer_4CF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_dispatch_source_set_runloop_timer_4CF()');
  },

  onLeave(log, retval, state) {
  }
});
