/*
 * Auto-generated by Frida. Please modify to match the signature of _dispatch_source_will_reenable_kevent_4NW.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_dispatch_source_will_reenable_kevent_4NW()');
  },

  onLeave(log, retval, state) {
  }
});
