/*
 * Auto-generated by Frida. Please modify to match the signature of dispatch_io_set_high_water.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('dispatch_io_set_high_water()');
  },

  onLeave(log, retval, state) {
  }
});
