/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN5zilch11GeoPolyline5resetENSt3__110shared_ptrIKNS1_6vectorINS_14GeoCoordinatesENS1_9allocatorIS4_EEEEEENS0_17GeometryDirectionE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN5zilch11GeoPolyline5resetENSt3__110shared_ptrIKNS1_6vectorINS_14GeoCoordinatesENS1_9allocatorIS4_EEEEEENS0_17GeometryDirectionE()');
  },

  onLeave(log, retval, state) {
  }
});
