/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN5zilch14GeoCoordinates3setENS_9LongitudeENS_8LatitudeEi.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN5zilch14GeoCoordinates3setENS_9LongitudeENS_8LatitudeEi()');
  },

  onLeave(log, retval, state) {
  }
});
