/*
 * Auto-generated by Frida. Please modify to match the signature of decode_heim_any_set.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('decode_heim_any_set()');
  },

  onLeave(log, retval, state) {
  }
});
