/*
 * Auto-generated by Frida. Please modify to match the signature of _os_activity_set_breadcrumb.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_os_activity_set_breadcrumb()');
  },

  onLeave(log, retval, state) {
  }
});
