/*
 * Auto-generated by Frida. Please modify to match the signature of $s6System14FileDescriptorV5_seek6offset4froms6ResultOys5Int64VAA5ErrnoVGAJ_AC10SeekOriginVtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s6System14FileDescriptorV5_seek6offset4froms6ResultOys5Int64VAA5ErrnoVGAJ_AC10SeekOriginVtF()');
  },

  onLeave(log, retval, state) {
  }
});
