/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7AMSCore13ProvisionTaskC2EONSt3__110unique_ptrINS_5IDataENS1_14default_deleteIS3_EEEEONS2_INS_13IMediaAccountENS4_IS8_EEEENS_17IFairPlayProvider12AnisetteTypeENS_3BagENS_11TaskOptionsE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7AMSCore13ProvisionTaskC2EONSt3__110unique_ptrINS_5IDataENS1_14default_deleteIS3_EEEEONS2_INS_13IMediaAccountENS4_IS8_EEEENS_17IFairPlayProvider12AnisetteTypeENS_3BagENS_11TaskOptionsE()');
  },

  onLeave(log, retval, state) {
  }
});
