/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7AMSCore21EncodeHTTPRequestTask14setIdentifiersERNS_12IHTTPRequestERKNS_13IMediaAccountERKNS_24EncodeHTTPRequestOptionsE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7AMSCore21EncodeHTTPRequestTask14setIdentifiersERNS_12IHTTPRequestERKNS_13IMediaAccountERKNS_24EncodeHTTPRequestOptionsE()');
  },

  onLeave(log, retval, state) {
  }
});
