/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7AMSCore22HTTPTransactionMetrics24setFormattedDNSAddressesENSt3__16vectorINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS6_IS8_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7AMSCore22HTTPTransactionMetrics24setFormattedDNSAddressesENSt3__16vectorINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS6_IS8_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
