/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7AMSCore3Bag23registerChangedObserverENSt3__110shared_ptrINS_9IObserverIJNS1_13unordered_setINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS1_4hashISA_EENS1_8equal_toISA_EENS8_ISA_EEEEEEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7AMSCore3Bag23registerChangedObserverENSt3__110shared_ptrINS_9IObserverIJNS1_13unordered_setINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS1_4hashISA_EENS1_8equal_toISA_EENS8_ISA_EEEEEEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
