/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7AMSCore22IAppleFairPlayProvider17eraseProvisioningERKNSt3__18optionalINS_15AccountIdentityEEENS_17IFairPlayProvider12AnisetteTypeE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7AMSCore22IAppleFairPlayProvider17eraseProvisioningERKNSt3__18optionalINS_15AccountIdentityEEENS_17IFairPlayProvider12AnisetteTypeE()');
  },

  onLeave(log, retval, state) {
  }
});
