/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7AMSCore13ProvisionTask31encodeFinishProvisioningRequestERKNS_5IDataEONSt3__110unique_ptrINS_13IMediaAccountENS4_14default_deleteIS6_EEEENS_17IFairPlayProvider12AnisetteTypeENS_3BagERKNS_7OptionsE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7AMSCore13ProvisionTask31encodeFinishProvisioningRequestERKNS_5IDataEONSt3__110unique_ptrINS_13IMediaAccountENS4_14default_deleteIS6_EEEENS_17IFairPlayProvider12AnisetteTypeENS_3BagERKNS_7OptionsE()');
  },

  onLeave(log, retval, state) {
  }
});
