/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN7AMSCore22HTTPTransactionMetrics20setResponseStartTimeENSt3__18optionalINS1_6chrono10time_pointINS3_12system_clockENS3_8durationIxNS1_5ratioILl1ELl1000000EEEEEEEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN7AMSCore22HTTPTransactionMetrics20setResponseStartTimeENSt3__18optionalINS1_6chrono10time_pointINS3_12system_clockENS3_8durationIxNS1_5ratioILl1ELl1000000EEEEEEEEE()');
  },

  onLeave(log, retval, state) {
  }
});
