/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV5ValueV13cleanAperture5width6height15horizontalOffet14verticalOffsetAGx_q_q0_q1_tSjRzSjR_SjR0_SjR1_r2_lFZ.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV5ValueV13cleanAperture5width6height15horizontalOffet14verticalOffsetAGx_q_q0_q1_tSjRzSjR_SjR0_SjR1_r2_lFZ()');
  },

  onLeave(log, retval, state) {
  }
});
