/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo13CMTimebaseRefa9CoreMediaE20setTimerNextFireTime_04fireI0ySo7NSTimerC_So6CMTimeatKF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo13CMTimebaseRefa9CoreMediaE20setTimerNextFireTime_04fireI0ySo7NSTimerC_So6CMTimeatKF()');
  },

  onLeave(log, retval, state) {
  }
});
