/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo17CMSampleBufferRefa9CoreMediaE07setDataB009fromAudioB4List05blockB15MemoryAllocator5flagsySPySo0ibJ0VG_So011CFAllocatorC0aSgAbCE5FlagsVtKF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo17CMSampleBufferRefa9CoreMediaE07setDataB009fromAudioB4List05blockB15MemoryAllocator5flagsySPySo0ibJ0VG_So011CFAllocatorC0aSgAbCE5FlagsVtKF()');
  },

  onLeave(log, retval, state) {
  }
});
