/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN9MaterialX16InterfaceElement18setConnectedOutputERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS1_10shared_ptrINS_6OutputEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN9MaterialX16InterfaceElement18setConnectedOutputERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS1_10shared_ptrINS_6OutputEEE()');
  },

  onLeave(log, retval, state) {
  }
});
