/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN9MaterialX10Collection20setIncludeCollectionENSt3__110shared_ptrIKS0_EE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN9MaterialX10Collection20setIncludeCollectionENSt3__110shared_ptrIKS0_EE()');
  },

  onLeave(log, retval, state) {
  }
});
