/*
 * Auto-generated by Frida. Please modify to match the signature of tcc_message_options_set_cache_policy.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('tcc_message_options_set_cache_policy()');
  },

  onLeave(log, retval, state) {
  }
});
