/*
 * Auto-generated by Frida. Please modify to match the signature of tcc_server_message_set_authorization_value.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('tcc_server_message_set_authorization_value()');
  },

  onLeave(log, retval, state) {
  }
});
