/*
 * Auto-generated by Frida. Please modify to match the signature of $s17_StringProcessing5RegexV5MatchV13dynamicMemberxs7KeyPathCyx_yt9_doNotUsetxG_tcig.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s17_StringProcessing5RegexV5MatchV13dynamicMemberxs7KeyPathCyx_yt9_doNotUsetxG_tcig()');
  },

  onLeave(log, retval, state) {
  }
});
