/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN2NU6Region10breakRectsERKNS_5RectTIlEES4_RNSt3__113unordered_setINS_10RegionRectENS_8RectHashENS_11RectEqualToENS5_9allocatorIS7_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN2NU6Region10breakRectsERKNS_5RectTIlEES4_RNSt3__113unordered_setINS_10RegionRectENS_8RectHashENS_11RectEqualToENS5_9allocatorIS7_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
