/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo24MTLComputeCommandEncoderP5MetalE16setSamplerStates_12lodMinClamps0h3MaxJ05rangeySaySo15MTLSamplerState_pSgG_SaySfGAKSnySiGtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo24MTLComputeCommandEncoderP5MetalE16setSamplerStates_12lodMinClamps0h3MaxJ05rangeySaySo15MTLSamplerState_pSgG_SaySfGAKSnySiGtF()');
  },

  onLeave(log, retval, state) {
  }
});
