/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo23MTLRenderPassDescriptorC5MetalE18setSamplePositionsyySaySo17MTLSamplePositionaGF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo23MTLRenderPassDescriptorC5MetalE18setSamplePositionsyySaySo17MTLSamplePositionaGF()');
  },

  onLeave(log, retval, state) {
  }
});
