/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo28MTLIntersectionFunctionTableP5MetalE010setVisibleB6Tables_11bufferRangeySaySo010MTLVisiblebC0_pSgG_SnySiGtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo28MTLIntersectionFunctionTableP5MetalE010setVisibleB6Tables_11bufferRangeySaySo010MTLVisiblebC0_pSgG_SnySiGtF()');
  },

  onLeave(log, retval, state) {
  }
});
