/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo21MTLBlitCommandEncoderP5MetalE15resolveCounters_5range17destinationBuffer0H6OffsetySo016MTLCounterSampleI0_p_SnySiGSo9MTLBuffer_pSitF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo21MTLBlitCommandEncoderP5MetalE15resolveCounters_5range17destinationBuffer0H6OffsetySo016MTLCounterSampleI0_p_SnySiGSo9MTLBuffer_pSitF()');
  },

  onLeave(log, retval, state) {
  }
});
