/*
 * Auto-generated by Frida. Please modify to match the signature of krb5_init_creds_set_pkinit_client_cert.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('krb5_init_creds_set_pkinit_client_cert()');
  },

  onLeave(log, retval, state) {
  }
});
