/*
 * Auto-generated by Frida. Please modify to match the signature of krb5_verify_opt_set_keytab.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('krb5_verify_opt_set_keytab()');
  },

  onLeave(log, retval, state) {
  }
});
