/*
 * Auto-generated by Frida. Please modify to match the signature of reset_com_err_hook.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('reset_com_err_hook()');
  },

  onLeave(log, retval, state) {
  }
});
