/*
 * Auto-generated by Frida. Please modify to match the signature of ep_session_set_procpid.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('ep_session_set_procpid()');
  },

  onLeave(log, retval, state) {
  }
});
