/*
 * Auto-generated by Frida. Please modify to match the signature of $s9PencilKit13PKStrokePointV8location10timeOffset4size7opacity5force7azimuth8altitudeACSo7CGPointV_SdSo6CGSizeV12CoreGraphics7CGFloatVA3QtcfC.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s9PencilKit13PKStrokePointV8location10timeOffset4size7opacity5force7azimuth8altitudeACSo7CGPointV_SdSo6CGSizeV12CoreGraphics7CGFloatVA3QtcfC()');
  },

  onLeave(log, retval, state) {
  }
});
