/*
 * Auto-generated by Frida. Please modify to match the signature of $s9PencilKit12PKStrokePathV15parametricValue_8offsetBy12CoreGraphics7CGFloatVAH_AC17InterpolatedSliceV6StrideOtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s9PencilKit12PKStrokePathV15parametricValue_8offsetBy12CoreGraphics7CGFloatVAH_AC17InterpolatedSliceV6StrideOtF()');
  },

  onLeave(log, retval, state) {
  }
});
