/*
 * Auto-generated by Frida. Please modify to match the signature of $s10Foundation14DateComponentsV8setValue_3forySiSg_AA8CalendarV9ComponentOtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s10Foundation14DateComponentsV8setValue_3forySiSg_AA8CalendarV9ComponentOtF()');
  },

  onLeave(log, retval, state) {
  }
});
