/*
 * Auto-generated by Frida. Please modify to match the signature of $s10Foundation8TimeZoneV014daylightSavingB6Offset3forSdAA4DateV_tF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s10Foundation8TimeZoneV014daylightSavingB6Offset3forSdAA4DateV_tF()');
  },

  onLeave(log, retval, state) {
  }
});
