/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo5NSSetC10FoundationE3setA2Bh_tcfC.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo5NSSetC10FoundationE3setA2Bh_tcfC()');
  },

  onLeave(log, retval, state) {
  }
});
