/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo12NSURLSessionC10FoundationE17DataTaskPublisherV7receive10subscriberyx_t7Combine10SubscriberRzAC8URLErrorV7FailureRtzAC0C0V4data_So13NSURLResponseC8responset5InputRtzlF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo12NSURLSessionC10FoundationE17DataTaskPublisherV7receive10subscriberyx_t7Combine10SubscriberRzAC8URLErrorV7FailureRtzAC0C0V4data_So13NSURLResponseC8responset5InputRtzlF()');
  },

  onLeave(log, retval, state) {
  }
});
