/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN10OpenSubdiv6v3_4_43Vtr8internal13TriRefinement34populateFaceVertexCountsAndOffsetsEv.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN10OpenSubdiv6v3_4_43Vtr8internal13TriRefinement34populateFaceVertexCountsAndOffsetsEv()');
  },

  onLeave(log, retval, state) {
  }
});
