/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK10OpenSubdiv6v3_4_43Far10PatchTable19GetPatchQuadOffsetsERKNS2_11PatchHandleE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK10OpenSubdiv6v3_4_43Far10PatchTable19GetPatchQuadOffsetsERKNS2_11PatchHandleE()');
  },

  onLeave(log, retval, state) {
  }
});
