/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3JSC2B39Procedure27setWasmBoundsCheckGeneratorEN3WTF6RefPtrINS2_10SharedTaskIFvRNS_12CCallHelpersENS_14ARM64Registers10RegisterIDEEEENS2_12RawPtrTraitsISA_EENS2_21DefaultRefDerefTraitsISA_EEEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN3JSC2B39Procedure27setWasmBoundsCheckGeneratorEN3WTF6RefPtrINS2_10SharedTaskIFvRNS_12CCallHelpersENS_14ARM64Registers10RegisterIDEEEENS2_12RawPtrTraitsISA_EENS2_21DefaultRefDerefTraitsISA_EEEE()');
  },

  onLeave(log, retval, state) {
  }
});
