/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3JSC4Wasm11LLIntCallee13setEntrypointENS_21MacroAssemblerCodePtrILN3WTF6PtrTagE9389EEE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN3JSC4Wasm11LLIntCallee13setEntrypointENS_21MacroAssemblerCodePtrILN3WTF6PtrTagE9389EEE()');
  },

  onLeave(log, retval, state) {
  }
});
