/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN3JSC8JSObject12setPrototypeEPS0_PNS_14JSGlobalObjectENS_7JSValueEb.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN3JSC8JSObject12setPrototypeEPS0_PNS_14JSGlobalObjectENS_7JSValueEb()');
  },

  onLeave(log, retval, state) {
  }
});
