/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK3JSC2B39Procedure30calleeSaveRegisterAtOffsetListEv.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK3JSC2B39Procedure30calleeSaveRegisterAtOffsetListEv()');
  },

  onLeave(log, retval, state) {
  }
});
