/*
 * Auto-generated by Frida. Please modify to match the signature of _ZThn16_N9Inspector22InspectorDebuggerAgent20setShouldBlackboxURLERKN3WTF6StringEbONSt3__18optionalIbEES8_.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZThn16_N9Inspector22InspectorDebuggerAgent20setShouldBlackboxURLERKN3WTF6StringEbONSt3__18optionalIbEES8_()');
  },

  onLeave(log, retval, state) {
  }
});
