/*
 * Auto-generated by Frida. Please modify to match the signature of $s12GameCenterUI27PlayerProfileViewControllerC7setRootyySo06PSRootG0CSgF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s12GameCenterUI27PlayerProfileViewControllerC7setRootyySo06PSRootG0CSgF()');
  },

  onLeave(log, retval, state) {
  }
});
