/*
 * Auto-generated by Frida. Please modify to match the signature of $s12GameCenterUI33GKMultiplayerViewControllerLayoutC19minimumContentInset2inSo12UIEdgeInsetsVSo012UICollectionE0C_tFZ.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s12GameCenterUI33GKMultiplayerViewControllerLayoutC19minimumContentInset2inSo12UIEdgeInsetsVSo012UICollectionE0C_tFZ()');
  },

  onLeave(log, retval, state) {
  }
});
