/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo23NSDirectionalEdgeInsetsV12GameCenterUIE25insetsWithLayoutDirectionySo06UIEdgeC0VSo018UITraitEnvironmentiJ0VF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo23NSDirectionalEdgeInsetsV12GameCenterUIE25insetsWithLayoutDirectionySo06UIEdgeC0VSo018UITraitEnvironmentiJ0VF()');
  },

  onLeave(log, retval, state) {
  }
});
