/*
 * Auto-generated by Frida. Please modify to match the signature of $s7CoreODI18ODISessionInternalC14setODNAtorTask33_19AF22E69F4D48D7EA827242BB7F5AA2LLScTyyts5Error_pGSgvpfi.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s7CoreODI18ODISessionInternalC14setODNAtorTask33_19AF22E69F4D48D7EA827242BB7F5AA2LLScTyyts5Error_pGSgvpfi()');
  },

  onLeave(log, retval, state) {
  }
});
