/*
 * Auto-generated by Frida. Please modify to match the signature of applejpeg_recode_set_option_jpeg_format.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('applejpeg_recode_set_option_jpeg_format()');
  },

  onLeave(log, retval, state) {
  }
});
