/*
 * Auto-generated by Frida. Please modify to match the signature of $s14CopresenceCore31ActivitySessionClientConnectionC8setState5state5errorySo010CPActivitydH0V_s5Error_pSgtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s14CopresenceCore31ActivitySessionClientConnectionC8setState5state5errorySo010CPActivitydH0V_s5Error_pSgtF()');
  },

  onLeave(log, retval, state) {
  }
});
