/*
 * Auto-generated by Frida. Please modify to match the signature of $s14CopresenceCore11CPAppPolicyO25GlobalAutoSharePlayToggleV7enabledSbvM.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s14CopresenceCore11CPAppPolicyO25GlobalAutoSharePlayToggleV7enabledSbvM()');
  },

  onLeave(log, retval, state) {
  }
});
