/*
 * Auto-generated by Frida. Please modify to match the signature of $s14CopresenceCore16ProtectedStorageP10setCodable_6forKeyyqd___SStSeRd__SERd__lFTj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s14CopresenceCore16ProtectedStorageP10setCodable_6forKeyyqd___SStSeRd__SERd__lFTj()');
  },

  onLeave(log, retval, state) {
  }
});
