/*
 * Auto-generated by Frida. Please modify to match the signature of $s14CopresenceCore31GroupSessionDataCryptorProviderC11setDelegate_5queueyAA05TopicfgI0_p_So012OS_dispatch_J0CtFTj.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s14CopresenceCore31GroupSessionDataCryptorProviderC11setDelegate_5queueyAA05TopicfgI0_p_So012OS_dispatch_J0CtFTj()');
  },

  onLeave(log, retval, state) {
  }
});
