/*
 * Auto-generated by Frida. Please modify to match the signature of _cdcontextstore_signpost_set_object_begin.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_cdcontextstore_signpost_set_object_begin()');
  },

  onLeave(log, retval, state) {
  }
});
