/*
 * Auto-generated by Frida. Please modify to match the signature of $s14GameKitWrapper31GKAchievement_ResetAchievements6taskId9onSuccess0I5Errorys5Int64V_yAGXCyAG_SpySo7NSErrorCGtXCtF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s14GameKitWrapper31GKAchievement_ResetAchievements6taskId9onSuccess0I5Errorys5Int64V_yAGXCyAG_SpySo7NSErrorCGtXCtF()');
  },

  onLeave(log, retval, state) {
  }
});
