/*
 * Auto-generated by Frida. Please modify to match the signature of _kernelrpc_mach_port_special_reply_port_reset_link.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_kernelrpc_mach_port_special_reply_port_reset_link()');
  },

  onLeave(log, retval, state) {
  }
});
