/*
 * Auto-generated by Frida. Please modify to match the signature of posix_spawnattr_set_portlimits_ext.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('posix_spawnattr_set_portlimits_ext()');
  },

  onLeave(log, retval, state) {
  }
});
