/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN12cnnavigation27GPSSatelliteClockOffsetRateEiddRKNS_14GPSEphemeridesERdbRNS_35GPSSatelliteClockOffsetRateJacobianE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN12cnnavigation27GPSSatelliteClockOffsetRateEiddRKNS_14GPSEphemeridesERdbRNS_35GPSSatelliteClockOffsetRateJacobianE()');
  },

  onLeave(log, retval, state) {
  }
});
