/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN14CoreNavigation3CLP8LogEntry10PublicData14MachTimeOffset10SharedCtorEv.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN14CoreNavigation3CLP8LogEntry10PublicData14MachTimeOffset10SharedCtorEv()');
  },

  onLeave(log, retval, state) {
  }
});
