/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN5raven21RavenSolutionSelector38ResetTunnelInformationForEstimatorTypeENS_18RavenEstimatorTypeE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN5raven21RavenSolutionSelector38ResetTunnelInformationForEstimatorTypeENS_18RavenEstimatorTypeE()');
  },

  onLeave(log, retval, state) {
  }
});
