/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN9cnlogging7details10ByteReader10setReadIdxERKx.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN9cnlogging7details10ByteReader10setReadIdxERKx()');
  },

  onLeave(log, retval, state) {
  }
});
