/*
 * Auto-generated by Frida. Please modify to match the signature of _ZNK12cnnavigation21PolynomialEphemerides24GNSSSatelliteClockOffsetERKNS_7TAITimeERKNS_17GNSSUTCParametersEdRdbRNS_32GNSSSatelliteClockOffsetJacobianE.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZNK12cnnavigation21PolynomialEphemerides24GNSSSatelliteClockOffsetERKNS_7TAITimeERKNS_17GNSSUTCParametersEdRdbRNS_32GNSSSatelliteClockOffsetJacobianE()');
  },

  onLeave(log, retval, state) {
  }
});
