/*
 * Auto-generated by Frida. Please modify to match the signature of $s10PegasusAPI11Amppb_OfferV6assetsSayAA0C6_AssetVGvs.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s10PegasusAPI11Amppb_OfferV6assetsSayAA0C6_AssetVGvs()');
  },

  onLeave(log, retval, state) {
  }
});
