/*
 * Auto-generated by Frida. Please modify to match the signature of _ZN9GDTYGNode27setLayoutLastOwnerDirectionE14GDTYGDirection.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_ZN9GDTYGNode27setLayoutLastOwnerDirectionE14GDTYGDirection()');
  },

  onLeave(log, retval, state) {
  }
});
