/*
 * Auto-generated by Frida. Please modify to match the signature of $s17CoreODIEssentials19DIPKeystoreProtocolPAAE29retrieveOrGenerateIdentityKey4name8userInfo09keyTypeToG09algorithm11constraints9enableUAMAA0hI0_pSS_SSAA08KeystoreiN0OAA15DIPKeyAlgorithmOSDyAA0hI16GenerationOptionOSSGSgSbtKF.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$s17CoreODIEssentials19DIPKeystoreProtocolPAAE29retrieveOrGenerateIdentityKey4name8userInfo09keyTypeToG09algorithm11constraints9enableUAMAA0hI0_pSS_SSAA08KeystoreiN0OAA15DIPKeyAlgorithmOSDyAA0hI16GenerationOptionOSSGSgSbtKF()');
  },

  onLeave(log, retval, state) {
  }
});
