/*
 * Auto-generated by Frida. Please modify to match the signature of si_set_nat64_v4_requires_synthesis.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('si_set_nat64_v4_requires_synthesis()');
  },

  onLeave(log, retval, state) {
  }
});
