/*
 * Auto-generated by Frida. Please modify to match the signature of kpc_force_all_ctrs_set.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('kpc_force_all_ctrs_set()');
  },

  onLeave(log, retval, state) {
  }
});
