/*
 * Auto-generated by Frida. Please modify to match the signature of remote_control_enable_network_peer.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('remote_control_enable_network_peer()');
  },

  onLeave(log, retval, state) {
  }
});
