/*
 * Auto-generated by Frida. Please modify to match the signature of $sSo28NSPersistentStoreCoordinatorC8CoreDataE11setMetadata_4type2at7optionsySDySSypGSg_So0aB0CACE0B4TypeV10Foundation3URLVSDys11AnyHashableVypGSgtKFZ.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('$sSo28NSPersistentStoreCoordinatorC8CoreDataE11setMetadata_4type2at7optionsySDySSypGSg_So0aB0CACE0B4TypeV10Foundation3URLVSDys11AnyHashableVypGSgtKFZ()');
  },

  onLeave(log, retval, state) {
  }
});
